/**
 * validatePhoneNumber
 *
 * Validates a local phone number against the selected country's rules
 * (min/max length, optional regex) from country_dial_codes. Designed to
 * run both client-side (live, on every keystroke, for immediate feedback)
 * and server-side (on save, as the authoritative check).
 *
 * This does NOT call the database directly — the country's validation
 * rules are passed in (fetched once per form load alongside the country
 * list), so this stays a pure, synchronous, easily-testable function.
 */

export interface CountryValidationRule {
  countryCode:       string;
  dialCode:          string;
  minLength:         number;
  maxLength:         number;
  localFormatRegex?: string | null;
}

export interface PhoneValidationResult {
  isValid: boolean;
  error?:  string;
}

/**
 * Strips all non-digit characters — spaces, dashes, parens — so the
 * caller can validate raw user input regardless of how they typed it.
 */
export function normalizePhoneDigits(rawInput: string): string {
  return rawInput.replace(/\D/g, '');
}

export function validatePhoneNumber(
  rawLocalNumber: string,
  rule: CountryValidationRule | null,
): PhoneValidationResult {
  if (!rule) {
    return { isValid: false, error: 'Select a country code first' };
  }

  const digits = normalizePhoneDigits(rawLocalNumber);

  if (digits.length === 0) {
    return { isValid: false, error: 'Phone number is required' };
  }

  if (digits.length < rule.minLength) {
    return {
      isValid: false,
      error: rule.minLength === rule.maxLength
        ? `Must be exactly ${rule.minLength} digits for ${rule.countryCode}`
        : `Must be at least ${rule.minLength} digits for ${rule.countryCode}`,
    };
  }

  if (digits.length > rule.maxLength) {
    return {
      isValid: false,
      error: rule.minLength === rule.maxLength
        ? `Must be exactly ${rule.maxLength} digits for ${rule.countryCode}`
        : `Must be at most ${rule.maxLength} digits for ${rule.countryCode}`,
    };
  }

  if (rule.localFormatRegex) {
    const re = new RegExp(rule.localFormatRegex);
    if (!re.test(digits)) {
      return {
        isValid: false,
        error: `Doesn't match the expected format for ${rule.countryCode} mobile numbers`,
      };
    }
  }

  return { isValid: true };
}

/**
 * Formats a raw digit string for DISPLAY only (not for storage — storage
 * always uses the raw digit string in phone_number). Provides simple
 * grouping for the most common formats; falls back to ungrouped digits
 * for countries without a specific format defined here.
 *
 * This is intentionally lightweight rather than a full libphonenumber
 * integration — sufficient for visual formatting as the user types,
 * matching the original spec's examples (+971 50 274 7733 / +44 7712 345678).
 */
export function formatPhoneForDisplay(digits: string, countryCode: string): string {
  const clean = normalizePhoneDigits(digits);

  switch (countryCode.toUpperCase()) {
    case 'AE': // +971 50 274 7733
      if (clean.length <= 2) return clean;
      if (clean.length <= 5) return `${clean.slice(0, 2)} ${clean.slice(2)}`;
      if (clean.length <= 8) return `${clean.slice(0, 2)} ${clean.slice(2, 5)} ${clean.slice(5)}`;
      return `${clean.slice(0, 2)} ${clean.slice(2, 5)} ${clean.slice(5, 9)}`;

    case 'GB': // +44 7712 345678
      if (clean.length <= 4) return clean;
      return `${clean.slice(0, 4)} ${clean.slice(4, 10)}`;

    case 'US':
    case 'CA': // +1 555 123 4567
      if (clean.length <= 3) return clean;
      if (clean.length <= 6) return `${clean.slice(0, 3)} ${clean.slice(3)}`;
      return `${clean.slice(0, 3)} ${clean.slice(3, 6)} ${clean.slice(6, 10)}`;

    default:
      // Generic grouping — chunks of 3 — readable fallback for any country
      // without an explicit format defined above.
      return clean.replace(/(\d{3})(?=\d)/g, '$1 ').trim();
  }
}

/**
 * Computes the full international number for storage in phone_full
 * display purposes (the DB column itself is auto-generated by migration
 * 025's GENERATED ALWAYS AS trigger — this is for client-side preview
 * before save, e.g. showing the user what will be stored).
 */
export function computeFullInternationalNumber(dialCode: string, localDigits: string): string {
  return `${dialCode}${normalizePhoneDigits(localDigits)}`;
}
