/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSmallBoatRegistrationRouteImport } from './routes/_app.small-boat-registration'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPackagesRouteImport } from './routes/_app.packages'
import { Route as AppOrbitRouteImport } from './routes/_app.orbit'
import { Route as AppDirectorRouteImport } from './routes/_app.director'
import { Route as AppCrewCabRouteImport } from './routes/_app.crew-cab'
import { Route as AppYachtsIndexRouteImport } from './routes/_app.yachts.index'
import { Route as AppYachtsNewRouteImport } from './routes/_app.yachts.new'
import { Route as AppYachtsIdRouteImport } from './routes/_app.yachts.$id'
import { Route as AppPermitsTdraRouteImport } from './routes/_app.permits.tdra'
import { Route as AppPermitsSanitationRouteImport } from './routes/_app.permits.sanitation'
import { Route as AppPermitsNavigationLicenseRouteImport } from './routes/_app.permits.navigation-license'
import { Route as AppPermitsGatePassRouteImport } from './routes/_app.permits.gate-pass'
import { Route as AppPermitsExitEntryRouteImport } from './routes/_app.permits.exit-entry'
import { Route as AppPermitsDmaRouteImport } from './routes/_app.permits.dma'
import { Route as AppPermitsCruisingTendersRouteImport } from './routes/_app.permits.cruising-tenders'
import { Route as AppPermitsCruisingMothershipRouteImport } from './routes/_app.permits.cruising-mothership'
import { Route as AppCrewCabVehiclesRouteImport } from './routes/_app.crew-cab.vehicles'
import { Route as AppCrewCabTripsRouteImport } from './routes/_app.crew-cab.trips'
import { Route as AppCrewCabLocationsRouteImport } from './routes/_app.crew-cab.locations'
import { Route as AppCrewCabDriversRouteImport } from './routes/_app.crew-cab.drivers'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSmallBoatRegistrationRoute =
  AppSmallBoatRegistrationRouteImport.update({
    id: '/small-boat-registration',
    path: '/small-boat-registration',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesRoute = AppPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AppRoute,
} as any)
const AppOrbitRoute = AppOrbitRouteImport.update({
  id: '/orbit',
  path: '/orbit',
  getParentRoute: () => AppRoute,
} as any)
const AppDirectorRoute = AppDirectorRouteImport.update({
  id: '/director',
  path: '/director',
  getParentRoute: () => AppRoute,
} as any)
const AppCrewCabRoute = AppCrewCabRouteImport.update({
  id: '/crew-cab',
  path: '/crew-cab',
  getParentRoute: () => AppRoute,
} as any)
const AppYachtsIndexRoute = AppYachtsIndexRouteImport.update({
  id: '/yachts/',
  path: '/yachts/',
  getParentRoute: () => AppRoute,
} as any)
const AppYachtsNewRoute = AppYachtsNewRouteImport.update({
  id: '/yachts/new',
  path: '/yachts/new',
  getParentRoute: () => AppRoute,
} as any)
const AppYachtsIdRoute = AppYachtsIdRouteImport.update({
  id: '/yachts/$id',
  path: '/yachts/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPermitsTdraRoute = AppPermitsTdraRouteImport.update({
  id: '/permits/tdra',
  path: '/permits/tdra',
  getParentRoute: () => AppRoute,
} as any)
const AppPermitsSanitationRoute = AppPermitsSanitationRouteImport.update({
  id: '/permits/sanitation',
  path: '/permits/sanitation',
  getParentRoute: () => AppRoute,
} as any)
const AppPermitsNavigationLicenseRoute =
  AppPermitsNavigationLicenseRouteImport.update({
    id: '/permits/navigation-license',
    path: '/permits/navigation-license',
    getParentRoute: () => AppRoute,
  } as any)
const AppPermitsGatePassRoute = AppPermitsGatePassRouteImport.update({
  id: '/permits/gate-pass',
  path: '/permits/gate-pass',
  getParentRoute: () => AppRoute,
} as any)
const AppPermitsExitEntryRoute = AppPermitsExitEntryRouteImport.update({
  id: '/permits/exit-entry',
  path: '/permits/exit-entry',
  getParentRoute: () => AppRoute,
} as any)
const AppPermitsDmaRoute = AppPermitsDmaRouteImport.update({
  id: '/permits/dma',
  path: '/permits/dma',
  getParentRoute: () => AppRoute,
} as any)
const AppPermitsCruisingTendersRoute =
  AppPermitsCruisingTendersRouteImport.update({
    id: '/permits/cruising-tenders',
    path: '/permits/cruising-tenders',
    getParentRoute: () => AppRoute,
  } as any)
const AppPermitsCruisingMothershipRoute =
  AppPermitsCruisingMothershipRouteImport.update({
    id: '/permits/cruising-mothership',
    path: '/permits/cruising-mothership',
    getParentRoute: () => AppRoute,
  } as any)
const AppCrewCabVehiclesRoute = AppCrewCabVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AppCrewCabRoute,
} as any)
const AppCrewCabTripsRoute = AppCrewCabTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AppCrewCabRoute,
} as any)
const AppCrewCabLocationsRoute = AppCrewCabLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppCrewCabRoute,
} as any)
const AppCrewCabDriversRoute = AppCrewCabDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AppCrewCabRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/crew-cab': typeof AppCrewCabRouteWithChildren
  '/director': typeof AppDirectorRoute
  '/orbit': typeof AppOrbitRoute
  '/packages': typeof AppPackagesRoute
  '/settings': typeof AppSettingsRoute
  '/small-boat-registration': typeof AppSmallBoatRegistrationRoute
  '/crew-cab/drivers': typeof AppCrewCabDriversRoute
  '/crew-cab/locations': typeof AppCrewCabLocationsRoute
  '/crew-cab/trips': typeof AppCrewCabTripsRoute
  '/crew-cab/vehicles': typeof AppCrewCabVehiclesRoute
  '/permits/cruising-mothership': typeof AppPermitsCruisingMothershipRoute
  '/permits/cruising-tenders': typeof AppPermitsCruisingTendersRoute
  '/permits/dma': typeof AppPermitsDmaRoute
  '/permits/exit-entry': typeof AppPermitsExitEntryRoute
  '/permits/gate-pass': typeof AppPermitsGatePassRoute
  '/permits/navigation-license': typeof AppPermitsNavigationLicenseRoute
  '/permits/sanitation': typeof AppPermitsSanitationRoute
  '/permits/tdra': typeof AppPermitsTdraRoute
  '/yachts/$id': typeof AppYachtsIdRoute
  '/yachts/new': typeof AppYachtsNewRoute
  '/yachts/': typeof AppYachtsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/crew-cab': typeof AppCrewCabRouteWithChildren
  '/director': typeof AppDirectorRoute
  '/orbit': typeof AppOrbitRoute
  '/packages': typeof AppPackagesRoute
  '/settings': typeof AppSettingsRoute
  '/small-boat-registration': typeof AppSmallBoatRegistrationRoute
  '/crew-cab/drivers': typeof AppCrewCabDriversRoute
  '/crew-cab/locations': typeof AppCrewCabLocationsRoute
  '/crew-cab/trips': typeof AppCrewCabTripsRoute
  '/crew-cab/vehicles': typeof AppCrewCabVehiclesRoute
  '/permits/cruising-mothership': typeof AppPermitsCruisingMothershipRoute
  '/permits/cruising-tenders': typeof AppPermitsCruisingTendersRoute
  '/permits/dma': typeof AppPermitsDmaRoute
  '/permits/exit-entry': typeof AppPermitsExitEntryRoute
  '/permits/gate-pass': typeof AppPermitsGatePassRoute
  '/permits/navigation-license': typeof AppPermitsNavigationLicenseRoute
  '/permits/sanitation': typeof AppPermitsSanitationRoute
  '/permits/tdra': typeof AppPermitsTdraRoute
  '/yachts/$id': typeof AppYachtsIdRoute
  '/yachts/new': typeof AppYachtsNewRoute
  '/yachts': typeof AppYachtsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/crew-cab': typeof AppCrewCabRouteWithChildren
  '/_app/director': typeof AppDirectorRoute
  '/_app/orbit': typeof AppOrbitRoute
  '/_app/packages': typeof AppPackagesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/small-boat-registration': typeof AppSmallBoatRegistrationRoute
  '/_app/crew-cab/drivers': typeof AppCrewCabDriversRoute
  '/_app/crew-cab/locations': typeof AppCrewCabLocationsRoute
  '/_app/crew-cab/trips': typeof AppCrewCabTripsRoute
  '/_app/crew-cab/vehicles': typeof AppCrewCabVehiclesRoute
  '/_app/permits/cruising-mothership': typeof AppPermitsCruisingMothershipRoute
  '/_app/permits/cruising-tenders': typeof AppPermitsCruisingTendersRoute
  '/_app/permits/dma': typeof AppPermitsDmaRoute
  '/_app/permits/exit-entry': typeof AppPermitsExitEntryRoute
  '/_app/permits/gate-pass': typeof AppPermitsGatePassRoute
  '/_app/permits/navigation-license': typeof AppPermitsNavigationLicenseRoute
  '/_app/permits/sanitation': typeof AppPermitsSanitationRoute
  '/_app/permits/tdra': typeof AppPermitsTdraRoute
  '/_app/yachts/$id': typeof AppYachtsIdRoute
  '/_app/yachts/new': typeof AppYachtsNewRoute
  '/_app/yachts/': typeof AppYachtsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/crew-cab'
    | '/director'
    | '/orbit'
    | '/packages'
    | '/settings'
    | '/small-boat-registration'
    | '/crew-cab/drivers'
    | '/crew-cab/locations'
    | '/crew-cab/trips'
    | '/crew-cab/vehicles'
    | '/permits/cruising-mothership'
    | '/permits/cruising-tenders'
    | '/permits/dma'
    | '/permits/exit-entry'
    | '/permits/gate-pass'
    | '/permits/navigation-license'
    | '/permits/sanitation'
    | '/permits/tdra'
    | '/yachts/$id'
    | '/yachts/new'
    | '/yachts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/crew-cab'
    | '/director'
    | '/orbit'
    | '/packages'
    | '/settings'
    | '/small-boat-registration'
    | '/crew-cab/drivers'
    | '/crew-cab/locations'
    | '/crew-cab/trips'
    | '/crew-cab/vehicles'
    | '/permits/cruising-mothership'
    | '/permits/cruising-tenders'
    | '/permits/dma'
    | '/permits/exit-entry'
    | '/permits/gate-pass'
    | '/permits/navigation-license'
    | '/permits/sanitation'
    | '/permits/tdra'
    | '/yachts/$id'
    | '/yachts/new'
    | '/yachts'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/crew-cab'
    | '/_app/director'
    | '/_app/orbit'
    | '/_app/packages'
    | '/_app/settings'
    | '/_app/small-boat-registration'
    | '/_app/crew-cab/drivers'
    | '/_app/crew-cab/locations'
    | '/_app/crew-cab/trips'
    | '/_app/crew-cab/vehicles'
    | '/_app/permits/cruising-mothership'
    | '/_app/permits/cruising-tenders'
    | '/_app/permits/dma'
    | '/_app/permits/exit-entry'
    | '/_app/permits/gate-pass'
    | '/_app/permits/navigation-license'
    | '/_app/permits/sanitation'
    | '/_app/permits/tdra'
    | '/_app/yachts/$id'
    | '/_app/yachts/new'
    | '/_app/yachts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/small-boat-registration': {
      id: '/_app/small-boat-registration'
      path: '/small-boat-registration'
      fullPath: '/small-boat-registration'
      preLoaderRoute: typeof AppSmallBoatRegistrationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/packages': {
      id: '/_app/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AppPackagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orbit': {
      id: '/_app/orbit'
      path: '/orbit'
      fullPath: '/orbit'
      preLoaderRoute: typeof AppOrbitRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/director': {
      id: '/_app/director'
      path: '/director'
      fullPath: '/director'
      preLoaderRoute: typeof AppDirectorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crew-cab': {
      id: '/_app/crew-cab'
      path: '/crew-cab'
      fullPath: '/crew-cab'
      preLoaderRoute: typeof AppCrewCabRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/yachts/': {
      id: '/_app/yachts/'
      path: '/yachts'
      fullPath: '/yachts/'
      preLoaderRoute: typeof AppYachtsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/yachts/new': {
      id: '/_app/yachts/new'
      path: '/yachts/new'
      fullPath: '/yachts/new'
      preLoaderRoute: typeof AppYachtsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/yachts/$id': {
      id: '/_app/yachts/$id'
      path: '/yachts/$id'
      fullPath: '/yachts/$id'
      preLoaderRoute: typeof AppYachtsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits/tdra': {
      id: '/_app/permits/tdra'
      path: '/permits/tdra'
      fullPath: '/permits/tdra'
      preLoaderRoute: typeof AppPermitsTdraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits/sanitation': {
      id: '/_app/permits/sanitation'
      path: '/permits/sanitation'
      fullPath: '/permits/sanitation'
      preLoaderRoute: typeof AppPermitsSanitationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits/navigation-license': {
      id: '/_app/permits/navigation-license'
      path: '/permits/navigation-license'
      fullPath: '/permits/navigation-license'
      preLoaderRoute: typeof AppPermitsNavigationLicenseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits/gate-pass': {
      id: '/_app/permits/gate-pass'
      path: '/permits/gate-pass'
      fullPath: '/permits/gate-pass'
      preLoaderRoute: typeof AppPermitsGatePassRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits/exit-entry': {
      id: '/_app/permits/exit-entry'
      path: '/permits/exit-entry'
      fullPath: '/permits/exit-entry'
      preLoaderRoute: typeof AppPermitsExitEntryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits/dma': {
      id: '/_app/permits/dma'
      path: '/permits/dma'
      fullPath: '/permits/dma'
      preLoaderRoute: typeof AppPermitsDmaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits/cruising-tenders': {
      id: '/_app/permits/cruising-tenders'
      path: '/permits/cruising-tenders'
      fullPath: '/permits/cruising-tenders'
      preLoaderRoute: typeof AppPermitsCruisingTendersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits/cruising-mothership': {
      id: '/_app/permits/cruising-mothership'
      path: '/permits/cruising-mothership'
      fullPath: '/permits/cruising-mothership'
      preLoaderRoute: typeof AppPermitsCruisingMothershipRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crew-cab/vehicles': {
      id: '/_app/crew-cab/vehicles'
      path: '/vehicles'
      fullPath: '/crew-cab/vehicles'
      preLoaderRoute: typeof AppCrewCabVehiclesRouteImport
      parentRoute: typeof AppCrewCabRoute
    }
    '/_app/crew-cab/trips': {
      id: '/_app/crew-cab/trips'
      path: '/trips'
      fullPath: '/crew-cab/trips'
      preLoaderRoute: typeof AppCrewCabTripsRouteImport
      parentRoute: typeof AppCrewCabRoute
    }
    '/_app/crew-cab/locations': {
      id: '/_app/crew-cab/locations'
      path: '/locations'
      fullPath: '/crew-cab/locations'
      preLoaderRoute: typeof AppCrewCabLocationsRouteImport
      parentRoute: typeof AppCrewCabRoute
    }
    '/_app/crew-cab/drivers': {
      id: '/_app/crew-cab/drivers'
      path: '/drivers'
      fullPath: '/crew-cab/drivers'
      preLoaderRoute: typeof AppCrewCabDriversRouteImport
      parentRoute: typeof AppCrewCabRoute
    }
  }
}

interface AppCrewCabRouteChildren {
  AppCrewCabDriversRoute: typeof AppCrewCabDriversRoute
  AppCrewCabLocationsRoute: typeof AppCrewCabLocationsRoute
  AppCrewCabTripsRoute: typeof AppCrewCabTripsRoute
  AppCrewCabVehiclesRoute: typeof AppCrewCabVehiclesRoute
}

const AppCrewCabRouteChildren: AppCrewCabRouteChildren = {
  AppCrewCabDriversRoute: AppCrewCabDriversRoute,
  AppCrewCabLocationsRoute: AppCrewCabLocationsRoute,
  AppCrewCabTripsRoute: AppCrewCabTripsRoute,
  AppCrewCabVehiclesRoute: AppCrewCabVehiclesRoute,
}

const AppCrewCabRouteWithChildren = AppCrewCabRoute._addFileChildren(
  AppCrewCabRouteChildren,
)

interface AppRouteChildren {
  AppCrewCabRoute: typeof AppCrewCabRouteWithChildren
  AppDirectorRoute: typeof AppDirectorRoute
  AppOrbitRoute: typeof AppOrbitRoute
  AppPackagesRoute: typeof AppPackagesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSmallBoatRegistrationRoute: typeof AppSmallBoatRegistrationRoute
  AppPermitsCruisingMothershipRoute: typeof AppPermitsCruisingMothershipRoute
  AppPermitsCruisingTendersRoute: typeof AppPermitsCruisingTendersRoute
  AppPermitsDmaRoute: typeof AppPermitsDmaRoute
  AppPermitsExitEntryRoute: typeof AppPermitsExitEntryRoute
  AppPermitsGatePassRoute: typeof AppPermitsGatePassRoute
  AppPermitsNavigationLicenseRoute: typeof AppPermitsNavigationLicenseRoute
  AppPermitsSanitationRoute: typeof AppPermitsSanitationRoute
  AppPermitsTdraRoute: typeof AppPermitsTdraRoute
  AppYachtsIdRoute: typeof AppYachtsIdRoute
  AppYachtsNewRoute: typeof AppYachtsNewRoute
  AppYachtsIndexRoute: typeof AppYachtsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCrewCabRoute: AppCrewCabRouteWithChildren,
  AppDirectorRoute: AppDirectorRoute,
  AppOrbitRoute: AppOrbitRoute,
  AppPackagesRoute: AppPackagesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSmallBoatRegistrationRoute: AppSmallBoatRegistrationRoute,
  AppPermitsCruisingMothershipRoute: AppPermitsCruisingMothershipRoute,
  AppPermitsCruisingTendersRoute: AppPermitsCruisingTendersRoute,
  AppPermitsDmaRoute: AppPermitsDmaRoute,
  AppPermitsExitEntryRoute: AppPermitsExitEntryRoute,
  AppPermitsGatePassRoute: AppPermitsGatePassRoute,
  AppPermitsNavigationLicenseRoute: AppPermitsNavigationLicenseRoute,
  AppPermitsSanitationRoute: AppPermitsSanitationRoute,
  AppPermitsTdraRoute: AppPermitsTdraRoute,
  AppYachtsIdRoute: AppYachtsIdRoute,
  AppYachtsNewRoute: AppYachtsNewRoute,
  AppYachtsIndexRoute: AppYachtsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
