/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignTokenRouteImport } from './routes/sign.$token'
import { Route as AppYachtItRouteImport } from './routes/_app.yacht-it'
import { Route as AppWaypointRouteImport } from './routes/_app.waypoint'
import { Route as AppTrainingRouteImport } from './routes/_app.training'
import { Route as AppSmallBoatRegistrationRouteImport } from './routes/_app.small-boat-registration'
import { Route as AppShipSparesRouteImport } from './routes/_app.ship-spares'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProvisioningRouteImport } from './routes/_app.provisioning'
import { Route as AppProcurementRouteImport } from './routes/_app.procurement'
import { Route as AppPackagesRouteImport } from './routes/_app.packages'
import { Route as AppOrbitRouteImport } from './routes/_app.orbit'
import { Route as AppMyFleetRouteImport } from './routes/_app.my-fleet'
import { Route as AppLicensingRouteImport } from './routes/_app.licensing'
import { Route as AppItYachtsRouteImport } from './routes/_app.it-yachts'
import { Route as AppItTicketsRouteImport } from './routes/_app.it-tickets'
import { Route as AppGuidesRouteImport } from './routes/_app.guides'
import { Route as AppFleetTrackingRouteImport } from './routes/_app.fleet-tracking'
import { Route as AppFinanceRouteImport } from './routes/_app.finance'
import { Route as AppEsignRouteImport } from './routes/_app.esign'
import { Route as AppDirectorRouteImport } from './routes/_app.director'
import { Route as AppDevSettingsRouteImport } from './routes/_app.dev-settings'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCrewPlacementRouteImport } from './routes/_app.crew-placement'
import { Route as AppCrewImmigrationRouteImport } from './routes/_app.crew-immigration'
import { Route as AppCrewCabRouteImport } from './routes/_app.crew-cab'
import { Route as AppCompassRouteImport } from './routes/_app.compass'
import { Route as AppChangelogRouteImport } from './routes/_app.changelog'
import { Route as AppAutomationsRouteImport } from './routes/_app.automations'
import { Route as AppAiAssistantRouteImport } from './routes/_app.ai-assistant'
import { Route as AppAgencyRouteImport } from './routes/_app.agency'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppYachtsIndexRouteImport } from './routes/_app.yachts.index'
import { Route as AppWaypointIndexRouteImport } from './routes/_app.waypoint.index'
import { Route as AppTrainingIndexRouteImport } from './routes/_app.training.index'
import { Route as AppPackagesIndexRouteImport } from './routes/_app.packages.index'
import { Route as AppOrbitIndexRouteImport } from './routes/_app.orbit.index'
import { Route as AppItTicketsIndexRouteImport } from './routes/_app.it-tickets.index'
import { Route as AppGuidesIndexRouteImport } from './routes/_app.guides.index'
import { Route as AppEsignIndexRouteImport } from './routes/_app.esign.index'
import { Route as AppCrewPlacementIndexRouteImport } from './routes/_app.crew-placement.index'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppYachtsNewRouteImport } from './routes/_app.yachts.new'
import { Route as AppYachtsIdRouteImport } from './routes/_app.yachts.$id'
import { Route as AppWaypointQuotationsRouteImport } from './routes/_app.waypoint.quotations'
import { Route as AppTrainingCertificationsRouteImport } from './routes/_app.training.certifications'
import { Route as AppPermitsTdraRouteImport } from './routes/_app.permits.tdra'
import { Route as AppPermitsSanitationRouteImport } from './routes/_app.permits.sanitation'
import { Route as AppPermitsNavigationLicenseRouteImport } from './routes/_app.permits.navigation-license'
import { Route as AppPermitsGatePassRouteImport } from './routes/_app.permits.gate-pass'
import { Route as AppPermitsExitEntryRouteImport } from './routes/_app.permits.exit-entry'
import { Route as AppPermitsDmaRouteImport } from './routes/_app.permits.dma'
import { Route as AppPermitsCruisingTendersRouteImport } from './routes/_app.permits.cruising-tenders'
import { Route as AppPermitsCruisingMothershipRouteImport } from './routes/_app.permits.cruising-mothership'
import { Route as AppPermitsCommandCentreRouteImport } from './routes/_app.permits.command-centre'
import { Route as AppPermitsAbuDhabiRouteImport } from './routes/_app.permits.abu-dhabi'
import { Route as AppPackagesDriversRouteImport } from './routes/_app.packages.drivers'
import { Route as AppPackagesDeliveriesRouteImport } from './routes/_app.packages.deliveries'
import { Route as AppOrbitMaintenanceRouteImport } from './routes/_app.orbit.maintenance'
import { Route as AppOrbitDefectsRouteImport } from './routes/_app.orbit.defects'
import { Route as AppOrbitProjectIdRouteImport } from './routes/_app.orbit.$projectId'
import { Route as AppItTicketsTicketIdRouteImport } from './routes/_app.it-tickets.$ticketId'
import { Route as AppGuidesDepartmentRouteImport } from './routes/_app.guides.$department'
import { Route as AppEsignDocumentIdRouteImport } from './routes/_app.esign.$documentId'
import { Route as AppCrewPlacementVacanciesRouteImport } from './routes/_app.crew-placement.vacancies'
import { Route as AppCrewImmigrationVisasRouteImport } from './routes/_app.crew-immigration.visas'
import { Route as AppCrewImmigrationSignOnOffRouteImport } from './routes/_app.crew-immigration.sign-on-off'
import { Route as AppCrewImmigrationDocumentsRouteImport } from './routes/_app.crew-immigration.documents'
import { Route as AppCrewImmigrationCrewRouteImport } from './routes/_app.crew-immigration.crew'
import { Route as AppCrewCabVehiclesRouteImport } from './routes/_app.crew-cab.vehicles'
import { Route as AppCrewCabTripsRouteImport } from './routes/_app.crew-cab.trips'
import { Route as AppCrewCabLocationsRouteImport } from './routes/_app.crew-cab.locations'
import { Route as AppCrewCabDriversRouteImport } from './routes/_app.crew-cab.drivers'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminPermissionsRouteImport } from './routes/_app.admin.permissions'
import { Route as AppAdminOrganisationsRouteImport } from './routes/_app.admin.organisations'
import { Route as AppAdminAuditRouteImport } from './routes/_app.admin.audit'
import { Route as AppGuidesDepartmentIndexRouteImport } from './routes/_app.guides.$department.index'
import { Route as AppCrewImmigrationVisasIndexRouteImport } from './routes/_app.crew-immigration.visas.index'
import { Route as AppGuidesDepartmentGuideIdRouteImport } from './routes/_app.guides.$department.$guideId'
import { Route as AppCrewImmigrationVisasNewRouteImport } from './routes/_app.crew-immigration.visas.new'
import { Route as AppCrewImmigrationVisasIdRouteImport } from './routes/_app.crew-immigration.visas.$id'
import { Route as AppCrewImmigrationCrewIdRouteImport } from './routes/_app.crew-immigration.crew.$id'
import { Route as AppCrewImmigrationVisasInfoCountryCodeRouteImport } from './routes/_app.crew-immigration.visas.info.$countryCode'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppYachtItRoute = AppYachtItRouteImport.update({
  id: '/yacht-it',
  path: '/yacht-it',
  getParentRoute: () => AppRoute,
} as any)
const AppWaypointRoute = AppWaypointRouteImport.update({
  id: '/waypoint',
  path: '/waypoint',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainingRoute = AppTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AppRoute,
} as any)
const AppSmallBoatRegistrationRoute =
  AppSmallBoatRegistrationRouteImport.update({
    id: '/small-boat-registration',
    path: '/small-boat-registration',
    getParentRoute: () => AppRoute,
  } as any)
const AppShipSparesRoute = AppShipSparesRouteImport.update({
  id: '/ship-spares',
  path: '/ship-spares',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProvisioningRoute = AppProvisioningRouteImport.update({
  id: '/provisioning',
  path: '/provisioning',
  getParentRoute: () => AppRoute,
} as any)
const AppProcurementRoute = AppProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesRoute = AppPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AppRoute,
} as any)
const AppOrbitRoute = AppOrbitRouteImport.update({
  id: '/orbit',
  path: '/orbit',
  getParentRoute: () => AppRoute,
} as any)
const AppMyFleetRoute = AppMyFleetRouteImport.update({
  id: '/my-fleet',
  path: '/my-fleet',
  getParentRoute: () => AppRoute,
} as any)
const AppLicensingRoute = AppLicensingRouteImport.update({
  id: '/licensing',
  path: '/licensing',
  getParentRoute: () => AppRoute,
} as any)
const AppItYachtsRoute = AppItYachtsRouteImport.update({
  id: '/it-yachts',
  path: '/it-yachts',
  getParentRoute: () => AppRoute,
} as any)
const AppItTicketsRoute = AppItTicketsRouteImport.update({
  id: '/it-tickets',
  path: '/it-tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppGuidesRoute = AppGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => AppRoute,
} as any)
const AppFleetTrackingRoute = AppFleetTrackingRouteImport.update({
  id: '/fleet-tracking',
  path: '/fleet-tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppEsignRoute = AppEsignRouteImport.update({
  id: '/esign',
  path: '/esign',
  getParentRoute: () => AppRoute,
} as any)
const AppDirectorRoute = AppDirectorRouteImport.update({
  id: '/director',
  path: '/director',
  getParentRoute: () => AppRoute,
} as any)
const AppDevSettingsRoute = AppDevSettingsRouteImport.update({
  id: '/dev-settings',
  path: '/dev-settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCrewPlacementRoute = AppCrewPlacementRouteImport.update({
  id: '/crew-placement',
  path: '/crew-placement',
  getParentRoute: () => AppRoute,
} as any)
const AppCrewImmigrationRoute = AppCrewImmigrationRouteImport.update({
  id: '/crew-immigration',
  path: '/crew-immigration',
  getParentRoute: () => AppRoute,
} as any)
const AppCrewCabRoute = AppCrewCabRouteImport.update({
  id: '/crew-cab',
  path: '/crew-cab',
  getParentRoute: () => AppRoute,
} as any)
const AppCompassRoute = AppCompassRouteImport.update({
  id: '/compass',
  path: '/compass',
  getParentRoute: () => AppRoute,
} as any)
const AppChangelogRoute = AppChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAssistantRoute = AppAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAgencyRoute = AppAgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppYachtsIndexRoute = AppYachtsIndexRouteImport.update({
  id: '/yachts/',
  path: '/yachts/',
  getParentRoute: () => AppRoute,
} as any)
const AppWaypointIndexRoute = AppWaypointIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWaypointRoute,
} as any)
const AppTrainingIndexRoute = AppTrainingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTrainingRoute,
} as any)
const AppPackagesIndexRoute = AppPackagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPackagesRoute,
} as any)
const AppOrbitIndexRoute = AppOrbitIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrbitRoute,
} as any)
const AppItTicketsIndexRoute = AppItTicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppItTicketsRoute,
} as any)
const AppGuidesIndexRoute = AppGuidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGuidesRoute,
} as any)
const AppEsignIndexRoute = AppEsignIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEsignRoute,
} as any)
const AppCrewPlacementIndexRoute = AppCrewPlacementIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCrewPlacementRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppYachtsNewRoute = AppYachtsNewRouteImport.update({
  id: '/yachts/new',
  path: '/yachts/new',
  getParentRoute: () => AppRoute,
} as any)
const AppYachtsIdRoute = AppYachtsIdRouteImport.update({
  id: '/yachts/$id',
  path: '/yachts/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppWaypointQuotationsRoute = AppWaypointQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppWaypointRoute,
} as any)
const AppTrainingCertificationsRoute =
  AppTrainingCertificationsRouteImport.update({
    id: '/certifications',
    path: '/certifications',
    getParentRoute: () => AppTrainingRoute,
  } as any)
const AppPermitsTdraRoute = AppPermitsTdraRouteImport.update({
  id: '/permits/tdra',
  path: '/permits/tdra',
  getParentRoute: () => AppRoute,
} as any)
const AppPermitsSanitationRoute = AppPermitsSanitationRouteImport.update({
  id: '/permits/sanitation',
  path: '/permits/sanitation',
  getParentRoute: () => AppRoute,
} as any)
const AppPermitsNavigationLicenseRoute =
  AppPermitsNavigationLicenseRouteImport.update({
    id: '/permits/navigation-license',
    path: '/permits/navigation-license',
    getParentRoute: () => AppRoute,
  } as any)
const AppPermitsGatePassRoute = AppPermitsGatePassRouteImport.update({
  id: '/permits/gate-pass',
  path: '/permits/gate-pass',
  getParentRoute: () => AppRoute,
} as any)
const AppPermitsExitEntryRoute = AppPermitsExitEntryRouteImport.update({
  id: '/permits/exit-entry',
  path: '/permits/exit-entry',
  getParentRoute: () => AppRoute,
} as any)
const AppPermitsDmaRoute = AppPermitsDmaRouteImport.update({
  id: '/permits/dma',
  path: '/permits/dma',
  getParentRoute: () => AppRoute,
} as any)
const AppPermitsCruisingTendersRoute =
  AppPermitsCruisingTendersRouteImport.update({
    id: '/permits/cruising-tenders',
    path: '/permits/cruising-tenders',
    getParentRoute: () => AppRoute,
  } as any)
const AppPermitsCruisingMothershipRoute =
  AppPermitsCruisingMothershipRouteImport.update({
    id: '/permits/cruising-mothership',
    path: '/permits/cruising-mothership',
    getParentRoute: () => AppRoute,
  } as any)
const AppPermitsCommandCentreRoute = AppPermitsCommandCentreRouteImport.update({
  id: '/permits/command-centre',
  path: '/permits/command-centre',
  getParentRoute: () => AppRoute,
} as any)
const AppPermitsAbuDhabiRoute = AppPermitsAbuDhabiRouteImport.update({
  id: '/permits/abu-dhabi',
  path: '/permits/abu-dhabi',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesDriversRoute = AppPackagesDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AppPackagesRoute,
} as any)
const AppPackagesDeliveriesRoute = AppPackagesDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AppPackagesRoute,
} as any)
const AppOrbitMaintenanceRoute = AppOrbitMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppOrbitRoute,
} as any)
const AppOrbitDefectsRoute = AppOrbitDefectsRouteImport.update({
  id: '/defects',
  path: '/defects',
  getParentRoute: () => AppOrbitRoute,
} as any)
const AppOrbitProjectIdRoute = AppOrbitProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppOrbitRoute,
} as any)
const AppItTicketsTicketIdRoute = AppItTicketsTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => AppItTicketsRoute,
} as any)
const AppGuidesDepartmentRoute = AppGuidesDepartmentRouteImport.update({
  id: '/$department',
  path: '/$department',
  getParentRoute: () => AppGuidesRoute,
} as any)
const AppEsignDocumentIdRoute = AppEsignDocumentIdRouteImport.update({
  id: '/$documentId',
  path: '/$documentId',
  getParentRoute: () => AppEsignRoute,
} as any)
const AppCrewPlacementVacanciesRoute =
  AppCrewPlacementVacanciesRouteImport.update({
    id: '/vacancies',
    path: '/vacancies',
    getParentRoute: () => AppCrewPlacementRoute,
  } as any)
const AppCrewImmigrationVisasRoute = AppCrewImmigrationVisasRouteImport.update({
  id: '/visas',
  path: '/visas',
  getParentRoute: () => AppCrewImmigrationRoute,
} as any)
const AppCrewImmigrationSignOnOffRoute =
  AppCrewImmigrationSignOnOffRouteImport.update({
    id: '/sign-on-off',
    path: '/sign-on-off',
    getParentRoute: () => AppCrewImmigrationRoute,
  } as any)
const AppCrewImmigrationDocumentsRoute =
  AppCrewImmigrationDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AppCrewImmigrationRoute,
  } as any)
const AppCrewImmigrationCrewRoute = AppCrewImmigrationCrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => AppCrewImmigrationRoute,
} as any)
const AppCrewCabVehiclesRoute = AppCrewCabVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AppCrewCabRoute,
} as any)
const AppCrewCabTripsRoute = AppCrewCabTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AppCrewCabRoute,
} as any)
const AppCrewCabLocationsRoute = AppCrewCabLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppCrewCabRoute,
} as any)
const AppCrewCabDriversRoute = AppCrewCabDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AppCrewCabRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPermissionsRoute = AppAdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminOrganisationsRoute = AppAdminOrganisationsRouteImport.update({
  id: '/organisations',
  path: '/organisations',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppGuidesDepartmentIndexRoute =
  AppGuidesDepartmentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppGuidesDepartmentRoute,
  } as any)
const AppCrewImmigrationVisasIndexRoute =
  AppCrewImmigrationVisasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppCrewImmigrationVisasRoute,
  } as any)
const AppGuidesDepartmentGuideIdRoute =
  AppGuidesDepartmentGuideIdRouteImport.update({
    id: '/$guideId',
    path: '/$guideId',
    getParentRoute: () => AppGuidesDepartmentRoute,
  } as any)
const AppCrewImmigrationVisasNewRoute =
  AppCrewImmigrationVisasNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AppCrewImmigrationVisasRoute,
  } as any)
const AppCrewImmigrationVisasIdRoute =
  AppCrewImmigrationVisasIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppCrewImmigrationVisasRoute,
  } as any)
const AppCrewImmigrationCrewIdRoute =
  AppCrewImmigrationCrewIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppCrewImmigrationCrewRoute,
  } as any)
const AppCrewImmigrationVisasInfoCountryCodeRoute =
  AppCrewImmigrationVisasInfoCountryCodeRouteImport.update({
    id: '/info/$countryCode',
    path: '/info/$countryCode',
    getParentRoute: () => AppCrewImmigrationVisasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/agency': typeof AppAgencyRoute
  '/ai-assistant': typeof AppAiAssistantRoute
  '/automations': typeof AppAutomationsRoute
  '/changelog': typeof AppChangelogRoute
  '/compass': typeof AppCompassRoute
  '/crew-cab': typeof AppCrewCabRouteWithChildren
  '/crew-immigration': typeof AppCrewImmigrationRouteWithChildren
  '/crew-placement': typeof AppCrewPlacementRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/dev-settings': typeof AppDevSettingsRoute
  '/director': typeof AppDirectorRoute
  '/esign': typeof AppEsignRouteWithChildren
  '/finance': typeof AppFinanceRoute
  '/fleet-tracking': typeof AppFleetTrackingRoute
  '/guides': typeof AppGuidesRouteWithChildren
  '/it-tickets': typeof AppItTicketsRouteWithChildren
  '/it-yachts': typeof AppItYachtsRoute
  '/licensing': typeof AppLicensingRoute
  '/my-fleet': typeof AppMyFleetRoute
  '/orbit': typeof AppOrbitRouteWithChildren
  '/packages': typeof AppPackagesRouteWithChildren
  '/procurement': typeof AppProcurementRoute
  '/provisioning': typeof AppProvisioningRoute
  '/settings': typeof AppSettingsRoute
  '/ship-spares': typeof AppShipSparesRoute
  '/small-boat-registration': typeof AppSmallBoatRegistrationRoute
  '/training': typeof AppTrainingRouteWithChildren
  '/waypoint': typeof AppWaypointRouteWithChildren
  '/yacht-it': typeof AppYachtItRoute
  '/sign/$token': typeof SignTokenRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/organisations': typeof AppAdminOrganisationsRoute
  '/admin/permissions': typeof AppAdminPermissionsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/crew-cab/drivers': typeof AppCrewCabDriversRoute
  '/crew-cab/locations': typeof AppCrewCabLocationsRoute
  '/crew-cab/trips': typeof AppCrewCabTripsRoute
  '/crew-cab/vehicles': typeof AppCrewCabVehiclesRoute
  '/crew-immigration/crew': typeof AppCrewImmigrationCrewRouteWithChildren
  '/crew-immigration/documents': typeof AppCrewImmigrationDocumentsRoute
  '/crew-immigration/sign-on-off': typeof AppCrewImmigrationSignOnOffRoute
  '/crew-immigration/visas': typeof AppCrewImmigrationVisasRouteWithChildren
  '/crew-placement/vacancies': typeof AppCrewPlacementVacanciesRoute
  '/esign/$documentId': typeof AppEsignDocumentIdRoute
  '/guides/$department': typeof AppGuidesDepartmentRouteWithChildren
  '/it-tickets/$ticketId': typeof AppItTicketsTicketIdRoute
  '/orbit/$projectId': typeof AppOrbitProjectIdRoute
  '/orbit/defects': typeof AppOrbitDefectsRoute
  '/orbit/maintenance': typeof AppOrbitMaintenanceRoute
  '/packages/deliveries': typeof AppPackagesDeliveriesRoute
  '/packages/drivers': typeof AppPackagesDriversRoute
  '/permits/abu-dhabi': typeof AppPermitsAbuDhabiRoute
  '/permits/command-centre': typeof AppPermitsCommandCentreRoute
  '/permits/cruising-mothership': typeof AppPermitsCruisingMothershipRoute
  '/permits/cruising-tenders': typeof AppPermitsCruisingTendersRoute
  '/permits/dma': typeof AppPermitsDmaRoute
  '/permits/exit-entry': typeof AppPermitsExitEntryRoute
  '/permits/gate-pass': typeof AppPermitsGatePassRoute
  '/permits/navigation-license': typeof AppPermitsNavigationLicenseRoute
  '/permits/sanitation': typeof AppPermitsSanitationRoute
  '/permits/tdra': typeof AppPermitsTdraRoute
  '/training/certifications': typeof AppTrainingCertificationsRoute
  '/waypoint/quotations': typeof AppWaypointQuotationsRoute
  '/yachts/$id': typeof AppYachtsIdRoute
  '/yachts/new': typeof AppYachtsNewRoute
  '/admin/': typeof AppAdminIndexRoute
  '/crew-placement/': typeof AppCrewPlacementIndexRoute
  '/esign/': typeof AppEsignIndexRoute
  '/guides/': typeof AppGuidesIndexRoute
  '/it-tickets/': typeof AppItTicketsIndexRoute
  '/orbit/': typeof AppOrbitIndexRoute
  '/packages/': typeof AppPackagesIndexRoute
  '/training/': typeof AppTrainingIndexRoute
  '/waypoint/': typeof AppWaypointIndexRoute
  '/yachts/': typeof AppYachtsIndexRoute
  '/crew-immigration/crew/$id': typeof AppCrewImmigrationCrewIdRoute
  '/crew-immigration/visas/$id': typeof AppCrewImmigrationVisasIdRoute
  '/crew-immigration/visas/new': typeof AppCrewImmigrationVisasNewRoute
  '/guides/$department/$guideId': typeof AppGuidesDepartmentGuideIdRoute
  '/crew-immigration/visas/': typeof AppCrewImmigrationVisasIndexRoute
  '/guides/$department/': typeof AppGuidesDepartmentIndexRoute
  '/crew-immigration/visas/info/$countryCode': typeof AppCrewImmigrationVisasInfoCountryCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agency': typeof AppAgencyRoute
  '/ai-assistant': typeof AppAiAssistantRoute
  '/automations': typeof AppAutomationsRoute
  '/changelog': typeof AppChangelogRoute
  '/compass': typeof AppCompassRoute
  '/crew-cab': typeof AppCrewCabRouteWithChildren
  '/crew-immigration': typeof AppCrewImmigrationRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/dev-settings': typeof AppDevSettingsRoute
  '/director': typeof AppDirectorRoute
  '/finance': typeof AppFinanceRoute
  '/fleet-tracking': typeof AppFleetTrackingRoute
  '/it-yachts': typeof AppItYachtsRoute
  '/licensing': typeof AppLicensingRoute
  '/my-fleet': typeof AppMyFleetRoute
  '/procurement': typeof AppProcurementRoute
  '/provisioning': typeof AppProvisioningRoute
  '/settings': typeof AppSettingsRoute
  '/ship-spares': typeof AppShipSparesRoute
  '/small-boat-registration': typeof AppSmallBoatRegistrationRoute
  '/yacht-it': typeof AppYachtItRoute
  '/sign/$token': typeof SignTokenRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/organisations': typeof AppAdminOrganisationsRoute
  '/admin/permissions': typeof AppAdminPermissionsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/crew-cab/drivers': typeof AppCrewCabDriversRoute
  '/crew-cab/locations': typeof AppCrewCabLocationsRoute
  '/crew-cab/trips': typeof AppCrewCabTripsRoute
  '/crew-cab/vehicles': typeof AppCrewCabVehiclesRoute
  '/crew-immigration/crew': typeof AppCrewImmigrationCrewRouteWithChildren
  '/crew-immigration/documents': typeof AppCrewImmigrationDocumentsRoute
  '/crew-immigration/sign-on-off': typeof AppCrewImmigrationSignOnOffRoute
  '/crew-placement/vacancies': typeof AppCrewPlacementVacanciesRoute
  '/esign/$documentId': typeof AppEsignDocumentIdRoute
  '/it-tickets/$ticketId': typeof AppItTicketsTicketIdRoute
  '/orbit/$projectId': typeof AppOrbitProjectIdRoute
  '/orbit/defects': typeof AppOrbitDefectsRoute
  '/orbit/maintenance': typeof AppOrbitMaintenanceRoute
  '/packages/deliveries': typeof AppPackagesDeliveriesRoute
  '/packages/drivers': typeof AppPackagesDriversRoute
  '/permits/abu-dhabi': typeof AppPermitsAbuDhabiRoute
  '/permits/command-centre': typeof AppPermitsCommandCentreRoute
  '/permits/cruising-mothership': typeof AppPermitsCruisingMothershipRoute
  '/permits/cruising-tenders': typeof AppPermitsCruisingTendersRoute
  '/permits/dma': typeof AppPermitsDmaRoute
  '/permits/exit-entry': typeof AppPermitsExitEntryRoute
  '/permits/gate-pass': typeof AppPermitsGatePassRoute
  '/permits/navigation-license': typeof AppPermitsNavigationLicenseRoute
  '/permits/sanitation': typeof AppPermitsSanitationRoute
  '/permits/tdra': typeof AppPermitsTdraRoute
  '/training/certifications': typeof AppTrainingCertificationsRoute
  '/waypoint/quotations': typeof AppWaypointQuotationsRoute
  '/yachts/$id': typeof AppYachtsIdRoute
  '/yachts/new': typeof AppYachtsNewRoute
  '/admin': typeof AppAdminIndexRoute
  '/crew-placement': typeof AppCrewPlacementIndexRoute
  '/esign': typeof AppEsignIndexRoute
  '/guides': typeof AppGuidesIndexRoute
  '/it-tickets': typeof AppItTicketsIndexRoute
  '/orbit': typeof AppOrbitIndexRoute
  '/packages': typeof AppPackagesIndexRoute
  '/training': typeof AppTrainingIndexRoute
  '/waypoint': typeof AppWaypointIndexRoute
  '/yachts': typeof AppYachtsIndexRoute
  '/crew-immigration/crew/$id': typeof AppCrewImmigrationCrewIdRoute
  '/crew-immigration/visas/$id': typeof AppCrewImmigrationVisasIdRoute
  '/crew-immigration/visas/new': typeof AppCrewImmigrationVisasNewRoute
  '/guides/$department/$guideId': typeof AppGuidesDepartmentGuideIdRoute
  '/crew-immigration/visas': typeof AppCrewImmigrationVisasIndexRoute
  '/guides/$department': typeof AppGuidesDepartmentIndexRoute
  '/crew-immigration/visas/info/$countryCode': typeof AppCrewImmigrationVisasInfoCountryCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/agency': typeof AppAgencyRoute
  '/_app/ai-assistant': typeof AppAiAssistantRoute
  '/_app/automations': typeof AppAutomationsRoute
  '/_app/changelog': typeof AppChangelogRoute
  '/_app/compass': typeof AppCompassRoute
  '/_app/crew-cab': typeof AppCrewCabRouteWithChildren
  '/_app/crew-immigration': typeof AppCrewImmigrationRouteWithChildren
  '/_app/crew-placement': typeof AppCrewPlacementRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/dev-settings': typeof AppDevSettingsRoute
  '/_app/director': typeof AppDirectorRoute
  '/_app/esign': typeof AppEsignRouteWithChildren
  '/_app/finance': typeof AppFinanceRoute
  '/_app/fleet-tracking': typeof AppFleetTrackingRoute
  '/_app/guides': typeof AppGuidesRouteWithChildren
  '/_app/it-tickets': typeof AppItTicketsRouteWithChildren
  '/_app/it-yachts': typeof AppItYachtsRoute
  '/_app/licensing': typeof AppLicensingRoute
  '/_app/my-fleet': typeof AppMyFleetRoute
  '/_app/orbit': typeof AppOrbitRouteWithChildren
  '/_app/packages': typeof AppPackagesRouteWithChildren
  '/_app/procurement': typeof AppProcurementRoute
  '/_app/provisioning': typeof AppProvisioningRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/ship-spares': typeof AppShipSparesRoute
  '/_app/small-boat-registration': typeof AppSmallBoatRegistrationRoute
  '/_app/training': typeof AppTrainingRouteWithChildren
  '/_app/waypoint': typeof AppWaypointRouteWithChildren
  '/_app/yacht-it': typeof AppYachtItRoute
  '/sign/$token': typeof SignTokenRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/organisations': typeof AppAdminOrganisationsRoute
  '/_app/admin/permissions': typeof AppAdminPermissionsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/crew-cab/drivers': typeof AppCrewCabDriversRoute
  '/_app/crew-cab/locations': typeof AppCrewCabLocationsRoute
  '/_app/crew-cab/trips': typeof AppCrewCabTripsRoute
  '/_app/crew-cab/vehicles': typeof AppCrewCabVehiclesRoute
  '/_app/crew-immigration/crew': typeof AppCrewImmigrationCrewRouteWithChildren
  '/_app/crew-immigration/documents': typeof AppCrewImmigrationDocumentsRoute
  '/_app/crew-immigration/sign-on-off': typeof AppCrewImmigrationSignOnOffRoute
  '/_app/crew-immigration/visas': typeof AppCrewImmigrationVisasRouteWithChildren
  '/_app/crew-placement/vacancies': typeof AppCrewPlacementVacanciesRoute
  '/_app/esign/$documentId': typeof AppEsignDocumentIdRoute
  '/_app/guides/$department': typeof AppGuidesDepartmentRouteWithChildren
  '/_app/it-tickets/$ticketId': typeof AppItTicketsTicketIdRoute
  '/_app/orbit/$projectId': typeof AppOrbitProjectIdRoute
  '/_app/orbit/defects': typeof AppOrbitDefectsRoute
  '/_app/orbit/maintenance': typeof AppOrbitMaintenanceRoute
  '/_app/packages/deliveries': typeof AppPackagesDeliveriesRoute
  '/_app/packages/drivers': typeof AppPackagesDriversRoute
  '/_app/permits/abu-dhabi': typeof AppPermitsAbuDhabiRoute
  '/_app/permits/command-centre': typeof AppPermitsCommandCentreRoute
  '/_app/permits/cruising-mothership': typeof AppPermitsCruisingMothershipRoute
  '/_app/permits/cruising-tenders': typeof AppPermitsCruisingTendersRoute
  '/_app/permits/dma': typeof AppPermitsDmaRoute
  '/_app/permits/exit-entry': typeof AppPermitsExitEntryRoute
  '/_app/permits/gate-pass': typeof AppPermitsGatePassRoute
  '/_app/permits/navigation-license': typeof AppPermitsNavigationLicenseRoute
  '/_app/permits/sanitation': typeof AppPermitsSanitationRoute
  '/_app/permits/tdra': typeof AppPermitsTdraRoute
  '/_app/training/certifications': typeof AppTrainingCertificationsRoute
  '/_app/waypoint/quotations': typeof AppWaypointQuotationsRoute
  '/_app/yachts/$id': typeof AppYachtsIdRoute
  '/_app/yachts/new': typeof AppYachtsNewRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/crew-placement/': typeof AppCrewPlacementIndexRoute
  '/_app/esign/': typeof AppEsignIndexRoute
  '/_app/guides/': typeof AppGuidesIndexRoute
  '/_app/it-tickets/': typeof AppItTicketsIndexRoute
  '/_app/orbit/': typeof AppOrbitIndexRoute
  '/_app/packages/': typeof AppPackagesIndexRoute
  '/_app/training/': typeof AppTrainingIndexRoute
  '/_app/waypoint/': typeof AppWaypointIndexRoute
  '/_app/yachts/': typeof AppYachtsIndexRoute
  '/_app/crew-immigration/crew/$id': typeof AppCrewImmigrationCrewIdRoute
  '/_app/crew-immigration/visas/$id': typeof AppCrewImmigrationVisasIdRoute
  '/_app/crew-immigration/visas/new': typeof AppCrewImmigrationVisasNewRoute
  '/_app/guides/$department/$guideId': typeof AppGuidesDepartmentGuideIdRoute
  '/_app/crew-immigration/visas/': typeof AppCrewImmigrationVisasIndexRoute
  '/_app/guides/$department/': typeof AppGuidesDepartmentIndexRoute
  '/_app/crew-immigration/visas/info/$countryCode': typeof AppCrewImmigrationVisasInfoCountryCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/agency'
    | '/ai-assistant'
    | '/automations'
    | '/changelog'
    | '/compass'
    | '/crew-cab'
    | '/crew-immigration'
    | '/crew-placement'
    | '/dashboard'
    | '/dev-settings'
    | '/director'
    | '/esign'
    | '/finance'
    | '/fleet-tracking'
    | '/guides'
    | '/it-tickets'
    | '/it-yachts'
    | '/licensing'
    | '/my-fleet'
    | '/orbit'
    | '/packages'
    | '/procurement'
    | '/provisioning'
    | '/settings'
    | '/ship-spares'
    | '/small-boat-registration'
    | '/training'
    | '/waypoint'
    | '/yacht-it'
    | '/sign/$token'
    | '/admin/audit'
    | '/admin/organisations'
    | '/admin/permissions'
    | '/admin/users'
    | '/crew-cab/drivers'
    | '/crew-cab/locations'
    | '/crew-cab/trips'
    | '/crew-cab/vehicles'
    | '/crew-immigration/crew'
    | '/crew-immigration/documents'
    | '/crew-immigration/sign-on-off'
    | '/crew-immigration/visas'
    | '/crew-placement/vacancies'
    | '/esign/$documentId'
    | '/guides/$department'
    | '/it-tickets/$ticketId'
    | '/orbit/$projectId'
    | '/orbit/defects'
    | '/orbit/maintenance'
    | '/packages/deliveries'
    | '/packages/drivers'
    | '/permits/abu-dhabi'
    | '/permits/command-centre'
    | '/permits/cruising-mothership'
    | '/permits/cruising-tenders'
    | '/permits/dma'
    | '/permits/exit-entry'
    | '/permits/gate-pass'
    | '/permits/navigation-license'
    | '/permits/sanitation'
    | '/permits/tdra'
    | '/training/certifications'
    | '/waypoint/quotations'
    | '/yachts/$id'
    | '/yachts/new'
    | '/admin/'
    | '/crew-placement/'
    | '/esign/'
    | '/guides/'
    | '/it-tickets/'
    | '/orbit/'
    | '/packages/'
    | '/training/'
    | '/waypoint/'
    | '/yachts/'
    | '/crew-immigration/crew/$id'
    | '/crew-immigration/visas/$id'
    | '/crew-immigration/visas/new'
    | '/guides/$department/$guideId'
    | '/crew-immigration/visas/'
    | '/guides/$department/'
    | '/crew-immigration/visas/info/$countryCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agency'
    | '/ai-assistant'
    | '/automations'
    | '/changelog'
    | '/compass'
    | '/crew-cab'
    | '/crew-immigration'
    | '/dashboard'
    | '/dev-settings'
    | '/director'
    | '/finance'
    | '/fleet-tracking'
    | '/it-yachts'
    | '/licensing'
    | '/my-fleet'
    | '/procurement'
    | '/provisioning'
    | '/settings'
    | '/ship-spares'
    | '/small-boat-registration'
    | '/yacht-it'
    | '/sign/$token'
    | '/admin/audit'
    | '/admin/organisations'
    | '/admin/permissions'
    | '/admin/users'
    | '/crew-cab/drivers'
    | '/crew-cab/locations'
    | '/crew-cab/trips'
    | '/crew-cab/vehicles'
    | '/crew-immigration/crew'
    | '/crew-immigration/documents'
    | '/crew-immigration/sign-on-off'
    | '/crew-placement/vacancies'
    | '/esign/$documentId'
    | '/it-tickets/$ticketId'
    | '/orbit/$projectId'
    | '/orbit/defects'
    | '/orbit/maintenance'
    | '/packages/deliveries'
    | '/packages/drivers'
    | '/permits/abu-dhabi'
    | '/permits/command-centre'
    | '/permits/cruising-mothership'
    | '/permits/cruising-tenders'
    | '/permits/dma'
    | '/permits/exit-entry'
    | '/permits/gate-pass'
    | '/permits/navigation-license'
    | '/permits/sanitation'
    | '/permits/tdra'
    | '/training/certifications'
    | '/waypoint/quotations'
    | '/yachts/$id'
    | '/yachts/new'
    | '/admin'
    | '/crew-placement'
    | '/esign'
    | '/guides'
    | '/it-tickets'
    | '/orbit'
    | '/packages'
    | '/training'
    | '/waypoint'
    | '/yachts'
    | '/crew-immigration/crew/$id'
    | '/crew-immigration/visas/$id'
    | '/crew-immigration/visas/new'
    | '/guides/$department/$guideId'
    | '/crew-immigration/visas'
    | '/guides/$department'
    | '/crew-immigration/visas/info/$countryCode'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/agency'
    | '/_app/ai-assistant'
    | '/_app/automations'
    | '/_app/changelog'
    | '/_app/compass'
    | '/_app/crew-cab'
    | '/_app/crew-immigration'
    | '/_app/crew-placement'
    | '/_app/dashboard'
    | '/_app/dev-settings'
    | '/_app/director'
    | '/_app/esign'
    | '/_app/finance'
    | '/_app/fleet-tracking'
    | '/_app/guides'
    | '/_app/it-tickets'
    | '/_app/it-yachts'
    | '/_app/licensing'
    | '/_app/my-fleet'
    | '/_app/orbit'
    | '/_app/packages'
    | '/_app/procurement'
    | '/_app/provisioning'
    | '/_app/settings'
    | '/_app/ship-spares'
    | '/_app/small-boat-registration'
    | '/_app/training'
    | '/_app/waypoint'
    | '/_app/yacht-it'
    | '/sign/$token'
    | '/_app/admin/audit'
    | '/_app/admin/organisations'
    | '/_app/admin/permissions'
    | '/_app/admin/users'
    | '/_app/crew-cab/drivers'
    | '/_app/crew-cab/locations'
    | '/_app/crew-cab/trips'
    | '/_app/crew-cab/vehicles'
    | '/_app/crew-immigration/crew'
    | '/_app/crew-immigration/documents'
    | '/_app/crew-immigration/sign-on-off'
    | '/_app/crew-immigration/visas'
    | '/_app/crew-placement/vacancies'
    | '/_app/esign/$documentId'
    | '/_app/guides/$department'
    | '/_app/it-tickets/$ticketId'
    | '/_app/orbit/$projectId'
    | '/_app/orbit/defects'
    | '/_app/orbit/maintenance'
    | '/_app/packages/deliveries'
    | '/_app/packages/drivers'
    | '/_app/permits/abu-dhabi'
    | '/_app/permits/command-centre'
    | '/_app/permits/cruising-mothership'
    | '/_app/permits/cruising-tenders'
    | '/_app/permits/dma'
    | '/_app/permits/exit-entry'
    | '/_app/permits/gate-pass'
    | '/_app/permits/navigation-license'
    | '/_app/permits/sanitation'
    | '/_app/permits/tdra'
    | '/_app/training/certifications'
    | '/_app/waypoint/quotations'
    | '/_app/yachts/$id'
    | '/_app/yachts/new'
    | '/_app/admin/'
    | '/_app/crew-placement/'
    | '/_app/esign/'
    | '/_app/guides/'
    | '/_app/it-tickets/'
    | '/_app/orbit/'
    | '/_app/packages/'
    | '/_app/training/'
    | '/_app/waypoint/'
    | '/_app/yachts/'
    | '/_app/crew-immigration/crew/$id'
    | '/_app/crew-immigration/visas/$id'
    | '/_app/crew-immigration/visas/new'
    | '/_app/guides/$department/$guideId'
    | '/_app/crew-immigration/visas/'
    | '/_app/guides/$department/'
    | '/_app/crew-immigration/visas/info/$countryCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  SignTokenRoute: typeof SignTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/yacht-it': {
      id: '/_app/yacht-it'
      path: '/yacht-it'
      fullPath: '/yacht-it'
      preLoaderRoute: typeof AppYachtItRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/waypoint': {
      id: '/_app/waypoint'
      path: '/waypoint'
      fullPath: '/waypoint'
      preLoaderRoute: typeof AppWaypointRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/training': {
      id: '/_app/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AppTrainingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/small-boat-registration': {
      id: '/_app/small-boat-registration'
      path: '/small-boat-registration'
      fullPath: '/small-boat-registration'
      preLoaderRoute: typeof AppSmallBoatRegistrationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ship-spares': {
      id: '/_app/ship-spares'
      path: '/ship-spares'
      fullPath: '/ship-spares'
      preLoaderRoute: typeof AppShipSparesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/provisioning': {
      id: '/_app/provisioning'
      path: '/provisioning'
      fullPath: '/provisioning'
      preLoaderRoute: typeof AppProvisioningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/procurement': {
      id: '/_app/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof AppProcurementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/packages': {
      id: '/_app/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AppPackagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orbit': {
      id: '/_app/orbit'
      path: '/orbit'
      fullPath: '/orbit'
      preLoaderRoute: typeof AppOrbitRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-fleet': {
      id: '/_app/my-fleet'
      path: '/my-fleet'
      fullPath: '/my-fleet'
      preLoaderRoute: typeof AppMyFleetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/licensing': {
      id: '/_app/licensing'
      path: '/licensing'
      fullPath: '/licensing'
      preLoaderRoute: typeof AppLicensingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/it-yachts': {
      id: '/_app/it-yachts'
      path: '/it-yachts'
      fullPath: '/it-yachts'
      preLoaderRoute: typeof AppItYachtsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/it-tickets': {
      id: '/_app/it-tickets'
      path: '/it-tickets'
      fullPath: '/it-tickets'
      preLoaderRoute: typeof AppItTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guides': {
      id: '/_app/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof AppGuidesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fleet-tracking': {
      id: '/_app/fleet-tracking'
      path: '/fleet-tracking'
      fullPath: '/fleet-tracking'
      preLoaderRoute: typeof AppFleetTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/esign': {
      id: '/_app/esign'
      path: '/esign'
      fullPath: '/esign'
      preLoaderRoute: typeof AppEsignRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/director': {
      id: '/_app/director'
      path: '/director'
      fullPath: '/director'
      preLoaderRoute: typeof AppDirectorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dev-settings': {
      id: '/_app/dev-settings'
      path: '/dev-settings'
      fullPath: '/dev-settings'
      preLoaderRoute: typeof AppDevSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crew-placement': {
      id: '/_app/crew-placement'
      path: '/crew-placement'
      fullPath: '/crew-placement'
      preLoaderRoute: typeof AppCrewPlacementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crew-immigration': {
      id: '/_app/crew-immigration'
      path: '/crew-immigration'
      fullPath: '/crew-immigration'
      preLoaderRoute: typeof AppCrewImmigrationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crew-cab': {
      id: '/_app/crew-cab'
      path: '/crew-cab'
      fullPath: '/crew-cab'
      preLoaderRoute: typeof AppCrewCabRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compass': {
      id: '/_app/compass'
      path: '/compass'
      fullPath: '/compass'
      preLoaderRoute: typeof AppCompassRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/changelog': {
      id: '/_app/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof AppChangelogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations': {
      id: '/_app/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-assistant': {
      id: '/_app/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AppAiAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agency': {
      id: '/_app/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AppAgencyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/yachts/': {
      id: '/_app/yachts/'
      path: '/yachts'
      fullPath: '/yachts/'
      preLoaderRoute: typeof AppYachtsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/waypoint/': {
      id: '/_app/waypoint/'
      path: '/'
      fullPath: '/waypoint/'
      preLoaderRoute: typeof AppWaypointIndexRouteImport
      parentRoute: typeof AppWaypointRoute
    }
    '/_app/training/': {
      id: '/_app/training/'
      path: '/'
      fullPath: '/training/'
      preLoaderRoute: typeof AppTrainingIndexRouteImport
      parentRoute: typeof AppTrainingRoute
    }
    '/_app/packages/': {
      id: '/_app/packages/'
      path: '/'
      fullPath: '/packages/'
      preLoaderRoute: typeof AppPackagesIndexRouteImport
      parentRoute: typeof AppPackagesRoute
    }
    '/_app/orbit/': {
      id: '/_app/orbit/'
      path: '/'
      fullPath: '/orbit/'
      preLoaderRoute: typeof AppOrbitIndexRouteImport
      parentRoute: typeof AppOrbitRoute
    }
    '/_app/it-tickets/': {
      id: '/_app/it-tickets/'
      path: '/'
      fullPath: '/it-tickets/'
      preLoaderRoute: typeof AppItTicketsIndexRouteImport
      parentRoute: typeof AppItTicketsRoute
    }
    '/_app/guides/': {
      id: '/_app/guides/'
      path: '/'
      fullPath: '/guides/'
      preLoaderRoute: typeof AppGuidesIndexRouteImport
      parentRoute: typeof AppGuidesRoute
    }
    '/_app/esign/': {
      id: '/_app/esign/'
      path: '/'
      fullPath: '/esign/'
      preLoaderRoute: typeof AppEsignIndexRouteImport
      parentRoute: typeof AppEsignRoute
    }
    '/_app/crew-placement/': {
      id: '/_app/crew-placement/'
      path: '/'
      fullPath: '/crew-placement/'
      preLoaderRoute: typeof AppCrewPlacementIndexRouteImport
      parentRoute: typeof AppCrewPlacementRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/yachts/new': {
      id: '/_app/yachts/new'
      path: '/yachts/new'
      fullPath: '/yachts/new'
      preLoaderRoute: typeof AppYachtsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/yachts/$id': {
      id: '/_app/yachts/$id'
      path: '/yachts/$id'
      fullPath: '/yachts/$id'
      preLoaderRoute: typeof AppYachtsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/waypoint/quotations': {
      id: '/_app/waypoint/quotations'
      path: '/quotations'
      fullPath: '/waypoint/quotations'
      preLoaderRoute: typeof AppWaypointQuotationsRouteImport
      parentRoute: typeof AppWaypointRoute
    }
    '/_app/training/certifications': {
      id: '/_app/training/certifications'
      path: '/certifications'
      fullPath: '/training/certifications'
      preLoaderRoute: typeof AppTrainingCertificationsRouteImport
      parentRoute: typeof AppTrainingRoute
    }
    '/_app/permits/tdra': {
      id: '/_app/permits/tdra'
      path: '/permits/tdra'
      fullPath: '/permits/tdra'
      preLoaderRoute: typeof AppPermitsTdraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits/sanitation': {
      id: '/_app/permits/sanitation'
      path: '/permits/sanitation'
      fullPath: '/permits/sanitation'
      preLoaderRoute: typeof AppPermitsSanitationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits/navigation-license': {
      id: '/_app/permits/navigation-license'
      path: '/permits/navigation-license'
      fullPath: '/permits/navigation-license'
      preLoaderRoute: typeof AppPermitsNavigationLicenseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits/gate-pass': {
      id: '/_app/permits/gate-pass'
      path: '/permits/gate-pass'
      fullPath: '/permits/gate-pass'
      preLoaderRoute: typeof AppPermitsGatePassRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits/exit-entry': {
      id: '/_app/permits/exit-entry'
      path: '/permits/exit-entry'
      fullPath: '/permits/exit-entry'
      preLoaderRoute: typeof AppPermitsExitEntryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits/dma': {
      id: '/_app/permits/dma'
      path: '/permits/dma'
      fullPath: '/permits/dma'
      preLoaderRoute: typeof AppPermitsDmaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits/cruising-tenders': {
      id: '/_app/permits/cruising-tenders'
      path: '/permits/cruising-tenders'
      fullPath: '/permits/cruising-tenders'
      preLoaderRoute: typeof AppPermitsCruisingTendersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits/cruising-mothership': {
      id: '/_app/permits/cruising-mothership'
      path: '/permits/cruising-mothership'
      fullPath: '/permits/cruising-mothership'
      preLoaderRoute: typeof AppPermitsCruisingMothershipRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits/command-centre': {
      id: '/_app/permits/command-centre'
      path: '/permits/command-centre'
      fullPath: '/permits/command-centre'
      preLoaderRoute: typeof AppPermitsCommandCentreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits/abu-dhabi': {
      id: '/_app/permits/abu-dhabi'
      path: '/permits/abu-dhabi'
      fullPath: '/permits/abu-dhabi'
      preLoaderRoute: typeof AppPermitsAbuDhabiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/packages/drivers': {
      id: '/_app/packages/drivers'
      path: '/drivers'
      fullPath: '/packages/drivers'
      preLoaderRoute: typeof AppPackagesDriversRouteImport
      parentRoute: typeof AppPackagesRoute
    }
    '/_app/packages/deliveries': {
      id: '/_app/packages/deliveries'
      path: '/deliveries'
      fullPath: '/packages/deliveries'
      preLoaderRoute: typeof AppPackagesDeliveriesRouteImport
      parentRoute: typeof AppPackagesRoute
    }
    '/_app/orbit/maintenance': {
      id: '/_app/orbit/maintenance'
      path: '/maintenance'
      fullPath: '/orbit/maintenance'
      preLoaderRoute: typeof AppOrbitMaintenanceRouteImport
      parentRoute: typeof AppOrbitRoute
    }
    '/_app/orbit/defects': {
      id: '/_app/orbit/defects'
      path: '/defects'
      fullPath: '/orbit/defects'
      preLoaderRoute: typeof AppOrbitDefectsRouteImport
      parentRoute: typeof AppOrbitRoute
    }
    '/_app/orbit/$projectId': {
      id: '/_app/orbit/$projectId'
      path: '/$projectId'
      fullPath: '/orbit/$projectId'
      preLoaderRoute: typeof AppOrbitProjectIdRouteImport
      parentRoute: typeof AppOrbitRoute
    }
    '/_app/it-tickets/$ticketId': {
      id: '/_app/it-tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/it-tickets/$ticketId'
      preLoaderRoute: typeof AppItTicketsTicketIdRouteImport
      parentRoute: typeof AppItTicketsRoute
    }
    '/_app/guides/$department': {
      id: '/_app/guides/$department'
      path: '/$department'
      fullPath: '/guides/$department'
      preLoaderRoute: typeof AppGuidesDepartmentRouteImport
      parentRoute: typeof AppGuidesRoute
    }
    '/_app/esign/$documentId': {
      id: '/_app/esign/$documentId'
      path: '/$documentId'
      fullPath: '/esign/$documentId'
      preLoaderRoute: typeof AppEsignDocumentIdRouteImport
      parentRoute: typeof AppEsignRoute
    }
    '/_app/crew-placement/vacancies': {
      id: '/_app/crew-placement/vacancies'
      path: '/vacancies'
      fullPath: '/crew-placement/vacancies'
      preLoaderRoute: typeof AppCrewPlacementVacanciesRouteImport
      parentRoute: typeof AppCrewPlacementRoute
    }
    '/_app/crew-immigration/visas': {
      id: '/_app/crew-immigration/visas'
      path: '/visas'
      fullPath: '/crew-immigration/visas'
      preLoaderRoute: typeof AppCrewImmigrationVisasRouteImport
      parentRoute: typeof AppCrewImmigrationRoute
    }
    '/_app/crew-immigration/sign-on-off': {
      id: '/_app/crew-immigration/sign-on-off'
      path: '/sign-on-off'
      fullPath: '/crew-immigration/sign-on-off'
      preLoaderRoute: typeof AppCrewImmigrationSignOnOffRouteImport
      parentRoute: typeof AppCrewImmigrationRoute
    }
    '/_app/crew-immigration/documents': {
      id: '/_app/crew-immigration/documents'
      path: '/documents'
      fullPath: '/crew-immigration/documents'
      preLoaderRoute: typeof AppCrewImmigrationDocumentsRouteImport
      parentRoute: typeof AppCrewImmigrationRoute
    }
    '/_app/crew-immigration/crew': {
      id: '/_app/crew-immigration/crew'
      path: '/crew'
      fullPath: '/crew-immigration/crew'
      preLoaderRoute: typeof AppCrewImmigrationCrewRouteImport
      parentRoute: typeof AppCrewImmigrationRoute
    }
    '/_app/crew-cab/vehicles': {
      id: '/_app/crew-cab/vehicles'
      path: '/vehicles'
      fullPath: '/crew-cab/vehicles'
      preLoaderRoute: typeof AppCrewCabVehiclesRouteImport
      parentRoute: typeof AppCrewCabRoute
    }
    '/_app/crew-cab/trips': {
      id: '/_app/crew-cab/trips'
      path: '/trips'
      fullPath: '/crew-cab/trips'
      preLoaderRoute: typeof AppCrewCabTripsRouteImport
      parentRoute: typeof AppCrewCabRoute
    }
    '/_app/crew-cab/locations': {
      id: '/_app/crew-cab/locations'
      path: '/locations'
      fullPath: '/crew-cab/locations'
      preLoaderRoute: typeof AppCrewCabLocationsRouteImport
      parentRoute: typeof AppCrewCabRoute
    }
    '/_app/crew-cab/drivers': {
      id: '/_app/crew-cab/drivers'
      path: '/drivers'
      fullPath: '/crew-cab/drivers'
      preLoaderRoute: typeof AppCrewCabDriversRouteImport
      parentRoute: typeof AppCrewCabRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/permissions': {
      id: '/_app/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AppAdminPermissionsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/organisations': {
      id: '/_app/admin/organisations'
      path: '/organisations'
      fullPath: '/admin/organisations'
      preLoaderRoute: typeof AppAdminOrganisationsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/guides/$department/': {
      id: '/_app/guides/$department/'
      path: '/'
      fullPath: '/guides/$department/'
      preLoaderRoute: typeof AppGuidesDepartmentIndexRouteImport
      parentRoute: typeof AppGuidesDepartmentRoute
    }
    '/_app/crew-immigration/visas/': {
      id: '/_app/crew-immigration/visas/'
      path: '/'
      fullPath: '/crew-immigration/visas/'
      preLoaderRoute: typeof AppCrewImmigrationVisasIndexRouteImport
      parentRoute: typeof AppCrewImmigrationVisasRoute
    }
    '/_app/guides/$department/$guideId': {
      id: '/_app/guides/$department/$guideId'
      path: '/$guideId'
      fullPath: '/guides/$department/$guideId'
      preLoaderRoute: typeof AppGuidesDepartmentGuideIdRouteImport
      parentRoute: typeof AppGuidesDepartmentRoute
    }
    '/_app/crew-immigration/visas/new': {
      id: '/_app/crew-immigration/visas/new'
      path: '/new'
      fullPath: '/crew-immigration/visas/new'
      preLoaderRoute: typeof AppCrewImmigrationVisasNewRouteImport
      parentRoute: typeof AppCrewImmigrationVisasRoute
    }
    '/_app/crew-immigration/visas/$id': {
      id: '/_app/crew-immigration/visas/$id'
      path: '/$id'
      fullPath: '/crew-immigration/visas/$id'
      preLoaderRoute: typeof AppCrewImmigrationVisasIdRouteImport
      parentRoute: typeof AppCrewImmigrationVisasRoute
    }
    '/_app/crew-immigration/crew/$id': {
      id: '/_app/crew-immigration/crew/$id'
      path: '/$id'
      fullPath: '/crew-immigration/crew/$id'
      preLoaderRoute: typeof AppCrewImmigrationCrewIdRouteImport
      parentRoute: typeof AppCrewImmigrationCrewRoute
    }
    '/_app/crew-immigration/visas/info/$countryCode': {
      id: '/_app/crew-immigration/visas/info/$countryCode'
      path: '/info/$countryCode'
      fullPath: '/crew-immigration/visas/info/$countryCode'
      preLoaderRoute: typeof AppCrewImmigrationVisasInfoCountryCodeRouteImport
      parentRoute: typeof AppCrewImmigrationVisasRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminOrganisationsRoute: typeof AppAdminOrganisationsRoute
  AppAdminPermissionsRoute: typeof AppAdminPermissionsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminOrganisationsRoute: AppAdminOrganisationsRoute,
  AppAdminPermissionsRoute: AppAdminPermissionsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppCrewCabRouteChildren {
  AppCrewCabDriversRoute: typeof AppCrewCabDriversRoute
  AppCrewCabLocationsRoute: typeof AppCrewCabLocationsRoute
  AppCrewCabTripsRoute: typeof AppCrewCabTripsRoute
  AppCrewCabVehiclesRoute: typeof AppCrewCabVehiclesRoute
}

const AppCrewCabRouteChildren: AppCrewCabRouteChildren = {
  AppCrewCabDriversRoute: AppCrewCabDriversRoute,
  AppCrewCabLocationsRoute: AppCrewCabLocationsRoute,
  AppCrewCabTripsRoute: AppCrewCabTripsRoute,
  AppCrewCabVehiclesRoute: AppCrewCabVehiclesRoute,
}

const AppCrewCabRouteWithChildren = AppCrewCabRoute._addFileChildren(
  AppCrewCabRouteChildren,
)

interface AppCrewImmigrationCrewRouteChildren {
  AppCrewImmigrationCrewIdRoute: typeof AppCrewImmigrationCrewIdRoute
}

const AppCrewImmigrationCrewRouteChildren: AppCrewImmigrationCrewRouteChildren =
  {
    AppCrewImmigrationCrewIdRoute: AppCrewImmigrationCrewIdRoute,
  }

const AppCrewImmigrationCrewRouteWithChildren =
  AppCrewImmigrationCrewRoute._addFileChildren(
    AppCrewImmigrationCrewRouteChildren,
  )

interface AppCrewImmigrationVisasRouteChildren {
  AppCrewImmigrationVisasIdRoute: typeof AppCrewImmigrationVisasIdRoute
  AppCrewImmigrationVisasNewRoute: typeof AppCrewImmigrationVisasNewRoute
  AppCrewImmigrationVisasIndexRoute: typeof AppCrewImmigrationVisasIndexRoute
  AppCrewImmigrationVisasInfoCountryCodeRoute: typeof AppCrewImmigrationVisasInfoCountryCodeRoute
}

const AppCrewImmigrationVisasRouteChildren: AppCrewImmigrationVisasRouteChildren =
  {
    AppCrewImmigrationVisasIdRoute: AppCrewImmigrationVisasIdRoute,
    AppCrewImmigrationVisasNewRoute: AppCrewImmigrationVisasNewRoute,
    AppCrewImmigrationVisasIndexRoute: AppCrewImmigrationVisasIndexRoute,
    AppCrewImmigrationVisasInfoCountryCodeRoute:
      AppCrewImmigrationVisasInfoCountryCodeRoute,
  }

const AppCrewImmigrationVisasRouteWithChildren =
  AppCrewImmigrationVisasRoute._addFileChildren(
    AppCrewImmigrationVisasRouteChildren,
  )

interface AppCrewImmigrationRouteChildren {
  AppCrewImmigrationCrewRoute: typeof AppCrewImmigrationCrewRouteWithChildren
  AppCrewImmigrationDocumentsRoute: typeof AppCrewImmigrationDocumentsRoute
  AppCrewImmigrationSignOnOffRoute: typeof AppCrewImmigrationSignOnOffRoute
  AppCrewImmigrationVisasRoute: typeof AppCrewImmigrationVisasRouteWithChildren
}

const AppCrewImmigrationRouteChildren: AppCrewImmigrationRouteChildren = {
  AppCrewImmigrationCrewRoute: AppCrewImmigrationCrewRouteWithChildren,
  AppCrewImmigrationDocumentsRoute: AppCrewImmigrationDocumentsRoute,
  AppCrewImmigrationSignOnOffRoute: AppCrewImmigrationSignOnOffRoute,
  AppCrewImmigrationVisasRoute: AppCrewImmigrationVisasRouteWithChildren,
}

const AppCrewImmigrationRouteWithChildren =
  AppCrewImmigrationRoute._addFileChildren(AppCrewImmigrationRouteChildren)

interface AppCrewPlacementRouteChildren {
  AppCrewPlacementVacanciesRoute: typeof AppCrewPlacementVacanciesRoute
  AppCrewPlacementIndexRoute: typeof AppCrewPlacementIndexRoute
}

const AppCrewPlacementRouteChildren: AppCrewPlacementRouteChildren = {
  AppCrewPlacementVacanciesRoute: AppCrewPlacementVacanciesRoute,
  AppCrewPlacementIndexRoute: AppCrewPlacementIndexRoute,
}

const AppCrewPlacementRouteWithChildren =
  AppCrewPlacementRoute._addFileChildren(AppCrewPlacementRouteChildren)

interface AppEsignRouteChildren {
  AppEsignDocumentIdRoute: typeof AppEsignDocumentIdRoute
  AppEsignIndexRoute: typeof AppEsignIndexRoute
}

const AppEsignRouteChildren: AppEsignRouteChildren = {
  AppEsignDocumentIdRoute: AppEsignDocumentIdRoute,
  AppEsignIndexRoute: AppEsignIndexRoute,
}

const AppEsignRouteWithChildren = AppEsignRoute._addFileChildren(
  AppEsignRouteChildren,
)

interface AppGuidesDepartmentRouteChildren {
  AppGuidesDepartmentGuideIdRoute: typeof AppGuidesDepartmentGuideIdRoute
  AppGuidesDepartmentIndexRoute: typeof AppGuidesDepartmentIndexRoute
}

const AppGuidesDepartmentRouteChildren: AppGuidesDepartmentRouteChildren = {
  AppGuidesDepartmentGuideIdRoute: AppGuidesDepartmentGuideIdRoute,
  AppGuidesDepartmentIndexRoute: AppGuidesDepartmentIndexRoute,
}

const AppGuidesDepartmentRouteWithChildren =
  AppGuidesDepartmentRoute._addFileChildren(AppGuidesDepartmentRouteChildren)

interface AppGuidesRouteChildren {
  AppGuidesDepartmentRoute: typeof AppGuidesDepartmentRouteWithChildren
  AppGuidesIndexRoute: typeof AppGuidesIndexRoute
}

const AppGuidesRouteChildren: AppGuidesRouteChildren = {
  AppGuidesDepartmentRoute: AppGuidesDepartmentRouteWithChildren,
  AppGuidesIndexRoute: AppGuidesIndexRoute,
}

const AppGuidesRouteWithChildren = AppGuidesRoute._addFileChildren(
  AppGuidesRouteChildren,
)

interface AppItTicketsRouteChildren {
  AppItTicketsTicketIdRoute: typeof AppItTicketsTicketIdRoute
  AppItTicketsIndexRoute: typeof AppItTicketsIndexRoute
}

const AppItTicketsRouteChildren: AppItTicketsRouteChildren = {
  AppItTicketsTicketIdRoute: AppItTicketsTicketIdRoute,
  AppItTicketsIndexRoute: AppItTicketsIndexRoute,
}

const AppItTicketsRouteWithChildren = AppItTicketsRoute._addFileChildren(
  AppItTicketsRouteChildren,
)

interface AppOrbitRouteChildren {
  AppOrbitProjectIdRoute: typeof AppOrbitProjectIdRoute
  AppOrbitDefectsRoute: typeof AppOrbitDefectsRoute
  AppOrbitMaintenanceRoute: typeof AppOrbitMaintenanceRoute
  AppOrbitIndexRoute: typeof AppOrbitIndexRoute
}

const AppOrbitRouteChildren: AppOrbitRouteChildren = {
  AppOrbitProjectIdRoute: AppOrbitProjectIdRoute,
  AppOrbitDefectsRoute: AppOrbitDefectsRoute,
  AppOrbitMaintenanceRoute: AppOrbitMaintenanceRoute,
  AppOrbitIndexRoute: AppOrbitIndexRoute,
}

const AppOrbitRouteWithChildren = AppOrbitRoute._addFileChildren(
  AppOrbitRouteChildren,
)

interface AppPackagesRouteChildren {
  AppPackagesDeliveriesRoute: typeof AppPackagesDeliveriesRoute
  AppPackagesDriversRoute: typeof AppPackagesDriversRoute
  AppPackagesIndexRoute: typeof AppPackagesIndexRoute
}

const AppPackagesRouteChildren: AppPackagesRouteChildren = {
  AppPackagesDeliveriesRoute: AppPackagesDeliveriesRoute,
  AppPackagesDriversRoute: AppPackagesDriversRoute,
  AppPackagesIndexRoute: AppPackagesIndexRoute,
}

const AppPackagesRouteWithChildren = AppPackagesRoute._addFileChildren(
  AppPackagesRouteChildren,
)

interface AppTrainingRouteChildren {
  AppTrainingCertificationsRoute: typeof AppTrainingCertificationsRoute
  AppTrainingIndexRoute: typeof AppTrainingIndexRoute
}

const AppTrainingRouteChildren: AppTrainingRouteChildren = {
  AppTrainingCertificationsRoute: AppTrainingCertificationsRoute,
  AppTrainingIndexRoute: AppTrainingIndexRoute,
}

const AppTrainingRouteWithChildren = AppTrainingRoute._addFileChildren(
  AppTrainingRouteChildren,
)

interface AppWaypointRouteChildren {
  AppWaypointQuotationsRoute: typeof AppWaypointQuotationsRoute
  AppWaypointIndexRoute: typeof AppWaypointIndexRoute
}

const AppWaypointRouteChildren: AppWaypointRouteChildren = {
  AppWaypointQuotationsRoute: AppWaypointQuotationsRoute,
  AppWaypointIndexRoute: AppWaypointIndexRoute,
}

const AppWaypointRouteWithChildren = AppWaypointRoute._addFileChildren(
  AppWaypointRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAgencyRoute: typeof AppAgencyRoute
  AppAiAssistantRoute: typeof AppAiAssistantRoute
  AppAutomationsRoute: typeof AppAutomationsRoute
  AppChangelogRoute: typeof AppChangelogRoute
  AppCompassRoute: typeof AppCompassRoute
  AppCrewCabRoute: typeof AppCrewCabRouteWithChildren
  AppCrewImmigrationRoute: typeof AppCrewImmigrationRouteWithChildren
  AppCrewPlacementRoute: typeof AppCrewPlacementRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDevSettingsRoute: typeof AppDevSettingsRoute
  AppDirectorRoute: typeof AppDirectorRoute
  AppEsignRoute: typeof AppEsignRouteWithChildren
  AppFinanceRoute: typeof AppFinanceRoute
  AppFleetTrackingRoute: typeof AppFleetTrackingRoute
  AppGuidesRoute: typeof AppGuidesRouteWithChildren
  AppItTicketsRoute: typeof AppItTicketsRouteWithChildren
  AppItYachtsRoute: typeof AppItYachtsRoute
  AppLicensingRoute: typeof AppLicensingRoute
  AppMyFleetRoute: typeof AppMyFleetRoute
  AppOrbitRoute: typeof AppOrbitRouteWithChildren
  AppPackagesRoute: typeof AppPackagesRouteWithChildren
  AppProcurementRoute: typeof AppProcurementRoute
  AppProvisioningRoute: typeof AppProvisioningRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShipSparesRoute: typeof AppShipSparesRoute
  AppSmallBoatRegistrationRoute: typeof AppSmallBoatRegistrationRoute
  AppTrainingRoute: typeof AppTrainingRouteWithChildren
  AppWaypointRoute: typeof AppWaypointRouteWithChildren
  AppYachtItRoute: typeof AppYachtItRoute
  AppPermitsAbuDhabiRoute: typeof AppPermitsAbuDhabiRoute
  AppPermitsCommandCentreRoute: typeof AppPermitsCommandCentreRoute
  AppPermitsCruisingMothershipRoute: typeof AppPermitsCruisingMothershipRoute
  AppPermitsCruisingTendersRoute: typeof AppPermitsCruisingTendersRoute
  AppPermitsDmaRoute: typeof AppPermitsDmaRoute
  AppPermitsExitEntryRoute: typeof AppPermitsExitEntryRoute
  AppPermitsGatePassRoute: typeof AppPermitsGatePassRoute
  AppPermitsNavigationLicenseRoute: typeof AppPermitsNavigationLicenseRoute
  AppPermitsSanitationRoute: typeof AppPermitsSanitationRoute
  AppPermitsTdraRoute: typeof AppPermitsTdraRoute
  AppYachtsIdRoute: typeof AppYachtsIdRoute
  AppYachtsNewRoute: typeof AppYachtsNewRoute
  AppYachtsIndexRoute: typeof AppYachtsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAgencyRoute: AppAgencyRoute,
  AppAiAssistantRoute: AppAiAssistantRoute,
  AppAutomationsRoute: AppAutomationsRoute,
  AppChangelogRoute: AppChangelogRoute,
  AppCompassRoute: AppCompassRoute,
  AppCrewCabRoute: AppCrewCabRouteWithChildren,
  AppCrewImmigrationRoute: AppCrewImmigrationRouteWithChildren,
  AppCrewPlacementRoute: AppCrewPlacementRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDevSettingsRoute: AppDevSettingsRoute,
  AppDirectorRoute: AppDirectorRoute,
  AppEsignRoute: AppEsignRouteWithChildren,
  AppFinanceRoute: AppFinanceRoute,
  AppFleetTrackingRoute: AppFleetTrackingRoute,
  AppGuidesRoute: AppGuidesRouteWithChildren,
  AppItTicketsRoute: AppItTicketsRouteWithChildren,
  AppItYachtsRoute: AppItYachtsRoute,
  AppLicensingRoute: AppLicensingRoute,
  AppMyFleetRoute: AppMyFleetRoute,
  AppOrbitRoute: AppOrbitRouteWithChildren,
  AppPackagesRoute: AppPackagesRouteWithChildren,
  AppProcurementRoute: AppProcurementRoute,
  AppProvisioningRoute: AppProvisioningRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShipSparesRoute: AppShipSparesRoute,
  AppSmallBoatRegistrationRoute: AppSmallBoatRegistrationRoute,
  AppTrainingRoute: AppTrainingRouteWithChildren,
  AppWaypointRoute: AppWaypointRouteWithChildren,
  AppYachtItRoute: AppYachtItRoute,
  AppPermitsAbuDhabiRoute: AppPermitsAbuDhabiRoute,
  AppPermitsCommandCentreRoute: AppPermitsCommandCentreRoute,
  AppPermitsCruisingMothershipRoute: AppPermitsCruisingMothershipRoute,
  AppPermitsCruisingTendersRoute: AppPermitsCruisingTendersRoute,
  AppPermitsDmaRoute: AppPermitsDmaRoute,
  AppPermitsExitEntryRoute: AppPermitsExitEntryRoute,
  AppPermitsGatePassRoute: AppPermitsGatePassRoute,
  AppPermitsNavigationLicenseRoute: AppPermitsNavigationLicenseRoute,
  AppPermitsSanitationRoute: AppPermitsSanitationRoute,
  AppPermitsTdraRoute: AppPermitsTdraRoute,
  AppYachtsIdRoute: AppYachtsIdRoute,
  AppYachtsNewRoute: AppYachtsNewRoute,
  AppYachtsIndexRoute: AppYachtsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  SignTokenRoute: SignTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
