/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppYachtItRouteImport } from './routes/_app.yacht-it'
import { Route as AppWaypointRouteImport } from './routes/_app.waypoint'
import { Route as AppTrainingRouteImport } from './routes/_app.training'
import { Route as AppSmallBoatRegistrationRouteImport } from './routes/_app.small-boat-registration'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProvisioningRouteImport } from './routes/_app.provisioning'
import { Route as AppProcurementRouteImport } from './routes/_app.procurement'
import { Route as AppPackagesRouteImport } from './routes/_app.packages'
import { Route as AppOrbitRouteImport } from './routes/_app.orbit'
import { Route as AppFleetTrackingRouteImport } from './routes/_app.fleet-tracking'
import { Route as AppFinanceRouteImport } from './routes/_app.finance'
import { Route as AppDirectorRouteImport } from './routes/_app.director'
import { Route as AppCrewPlacementRouteImport } from './routes/_app.crew-placement'
import { Route as AppCrewImmigrationRouteImport } from './routes/_app.crew-immigration'
import { Route as AppCrewCabRouteImport } from './routes/_app.crew-cab'
import { Route as AppCompassRouteImport } from './routes/_app.compass'
import { Route as AppChangelogRouteImport } from './routes/_app.changelog'
import { Route as AppAiAssistantRouteImport } from './routes/_app.ai-assistant'
import { Route as AppYachtsIndexRouteImport } from './routes/_app.yachts.index'
import { Route as AppPackagesIndexRouteImport } from './routes/_app.packages.index'
import { Route as AppOrbitIndexRouteImport } from './routes/_app.orbit.index'
import { Route as AppYachtsNewRouteImport } from './routes/_app.yachts.new'
import { Route as AppYachtsIdRouteImport } from './routes/_app.yachts.$id'
import { Route as AppPermitsTdraRouteImport } from './routes/_app.permits.tdra'
import { Route as AppPermitsSanitationRouteImport } from './routes/_app.permits.sanitation'
import { Route as AppPermitsNavigationLicenseRouteImport } from './routes/_app.permits.navigation-license'
import { Route as AppPermitsGatePassRouteImport } from './routes/_app.permits.gate-pass'
import { Route as AppPermitsExitEntryRouteImport } from './routes/_app.permits.exit-entry'
import { Route as AppPermitsDmaRouteImport } from './routes/_app.permits.dma'
import { Route as AppPermitsCruisingTendersRouteImport } from './routes/_app.permits.cruising-tenders'
import { Route as AppPermitsCruisingMothershipRouteImport } from './routes/_app.permits.cruising-mothership'
import { Route as AppPermitsAbuDhabiRouteImport } from './routes/_app.permits.abu-dhabi'
import { Route as AppPackagesDriversRouteImport } from './routes/_app.packages.drivers'
import { Route as AppPackagesDeliveriesRouteImport } from './routes/_app.packages.deliveries'
import { Route as AppOrbitProjectIdRouteImport } from './routes/_app.orbit.$projectId'
import { Route as AppCrewImmigrationVisasRouteImport } from './routes/_app.crew-immigration.visas'
import { Route as AppCrewImmigrationSignOnOffRouteImport } from './routes/_app.crew-immigration.sign-on-off'
import { Route as AppCrewImmigrationDocumentsRouteImport } from './routes/_app.crew-immigration.documents'
import { Route as AppCrewImmigrationCrewRouteImport } from './routes/_app.crew-immigration.crew'
import { Route as AppCrewCabVehiclesRouteImport } from './routes/_app.crew-cab.vehicles'
import { Route as AppCrewCabTripsRouteImport } from './routes/_app.crew-cab.trips'
import { Route as AppCrewCabLocationsRouteImport } from './routes/_app.crew-cab.locations'
import { Route as AppCrewCabDriversRouteImport } from './routes/_app.crew-cab.drivers'
import { Route as AppCrewImmigrationVisasNewRouteImport } from './routes/_app.crew-immigration.visas.new'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppYachtItRoute = AppYachtItRouteImport.update({
  id: '/yacht-it',
  path: '/yacht-it',
  getParentRoute: () => AppRoute,
} as any)
const AppWaypointRoute = AppWaypointRouteImport.update({
  id: '/waypoint',
  path: '/waypoint',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainingRoute = AppTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AppRoute,
} as any)
const AppSmallBoatRegistrationRoute =
  AppSmallBoatRegistrationRouteImport.update({
    id: '/small-boat-registration',
    path: '/small-boat-registration',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProvisioningRoute = AppProvisioningRouteImport.update({
  id: '/provisioning',
  path: '/provisioning',
  getParentRoute: () => AppRoute,
} as any)
const AppProcurementRoute = AppProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesRoute = AppPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AppRoute,
} as any)
const AppOrbitRoute = AppOrbitRouteImport.update({
  id: '/orbit',
  path: '/orbit',
  getParentRoute: () => AppRoute,
} as any)
const AppFleetTrackingRoute = AppFleetTrackingRouteImport.update({
  id: '/fleet-tracking',
  path: '/fleet-tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppDirectorRoute = AppDirectorRouteImport.update({
  id: '/director',
  path: '/director',
  getParentRoute: () => AppRoute,
} as any)
const AppCrewPlacementRoute = AppCrewPlacementRouteImport.update({
  id: '/crew-placement',
  path: '/crew-placement',
  getParentRoute: () => AppRoute,
} as any)
const AppCrewImmigrationRoute = AppCrewImmigrationRouteImport.update({
  id: '/crew-immigration',
  path: '/crew-immigration',
  getParentRoute: () => AppRoute,
} as any)
const AppCrewCabRoute = AppCrewCabRouteImport.update({
  id: '/crew-cab',
  path: '/crew-cab',
  getParentRoute: () => AppRoute,
} as any)
const AppCompassRoute = AppCompassRouteImport.update({
  id: '/compass',
  path: '/compass',
  getParentRoute: () => AppRoute,
} as any)
const AppChangelogRoute = AppChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAssistantRoute = AppAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppYachtsIndexRoute = AppYachtsIndexRouteImport.update({
  id: '/yachts/',
  path: '/yachts/',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesIndexRoute = AppPackagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPackagesRoute,
} as any)
const AppOrbitIndexRoute = AppOrbitIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrbitRoute,
} as any)
const AppYachtsNewRoute = AppYachtsNewRouteImport.update({
  id: '/yachts/new',
  path: '/yachts/new',
  getParentRoute: () => AppRoute,
} as any)
const AppYachtsIdRoute = AppYachtsIdRouteImport.update({
  id: '/yachts/$id',
  path: '/yachts/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPermitsTdraRoute = AppPermitsTdraRouteImport.update({
  id: '/permits/tdra',
  path: '/permits/tdra',
  getParentRoute: () => AppRoute,
} as any)
const AppPermitsSanitationRoute = AppPermitsSanitationRouteImport.update({
  id: '/permits/sanitation',
  path: '/permits/sanitation',
  getParentRoute: () => AppRoute,
} as any)
const AppPermitsNavigationLicenseRoute =
  AppPermitsNavigationLicenseRouteImport.update({
    id: '/permits/navigation-license',
    path: '/permits/navigation-license',
    getParentRoute: () => AppRoute,
  } as any)
const AppPermitsGatePassRoute = AppPermitsGatePassRouteImport.update({
  id: '/permits/gate-pass',
  path: '/permits/gate-pass',
  getParentRoute: () => AppRoute,
} as any)
const AppPermitsExitEntryRoute = AppPermitsExitEntryRouteImport.update({
  id: '/permits/exit-entry',
  path: '/permits/exit-entry',
  getParentRoute: () => AppRoute,
} as any)
const AppPermitsDmaRoute = AppPermitsDmaRouteImport.update({
  id: '/permits/dma',
  path: '/permits/dma',
  getParentRoute: () => AppRoute,
} as any)
const AppPermitsCruisingTendersRoute =
  AppPermitsCruisingTendersRouteImport.update({
    id: '/permits/cruising-tenders',
    path: '/permits/cruising-tenders',
    getParentRoute: () => AppRoute,
  } as any)
const AppPermitsCruisingMothershipRoute =
  AppPermitsCruisingMothershipRouteImport.update({
    id: '/permits/cruising-mothership',
    path: '/permits/cruising-mothership',
    getParentRoute: () => AppRoute,
  } as any)
const AppPermitsAbuDhabiRoute = AppPermitsAbuDhabiRouteImport.update({
  id: '/permits/abu-dhabi',
  path: '/permits/abu-dhabi',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesDriversRoute = AppPackagesDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AppPackagesRoute,
} as any)
const AppPackagesDeliveriesRoute = AppPackagesDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AppPackagesRoute,
} as any)
const AppOrbitProjectIdRoute = AppOrbitProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppOrbitRoute,
} as any)
const AppCrewImmigrationVisasRoute = AppCrewImmigrationVisasRouteImport.update({
  id: '/visas',
  path: '/visas',
  getParentRoute: () => AppCrewImmigrationRoute,
} as any)
const AppCrewImmigrationSignOnOffRoute =
  AppCrewImmigrationSignOnOffRouteImport.update({
    id: '/sign-on-off',
    path: '/sign-on-off',
    getParentRoute: () => AppCrewImmigrationRoute,
  } as any)
const AppCrewImmigrationDocumentsRoute =
  AppCrewImmigrationDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AppCrewImmigrationRoute,
  } as any)
const AppCrewImmigrationCrewRoute = AppCrewImmigrationCrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => AppCrewImmigrationRoute,
} as any)
const AppCrewCabVehiclesRoute = AppCrewCabVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AppCrewCabRoute,
} as any)
const AppCrewCabTripsRoute = AppCrewCabTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AppCrewCabRoute,
} as any)
const AppCrewCabLocationsRoute = AppCrewCabLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppCrewCabRoute,
} as any)
const AppCrewCabDriversRoute = AppCrewCabDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AppCrewCabRoute,
} as any)
const AppCrewImmigrationVisasNewRoute =
  AppCrewImmigrationVisasNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AppCrewImmigrationVisasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-assistant': typeof AppAiAssistantRoute
  '/changelog': typeof AppChangelogRoute
  '/compass': typeof AppCompassRoute
  '/crew-cab': typeof AppCrewCabRouteWithChildren
  '/crew-immigration': typeof AppCrewImmigrationRouteWithChildren
  '/crew-placement': typeof AppCrewPlacementRoute
  '/director': typeof AppDirectorRoute
  '/finance': typeof AppFinanceRoute
  '/fleet-tracking': typeof AppFleetTrackingRoute
  '/orbit': typeof AppOrbitRouteWithChildren
  '/packages': typeof AppPackagesRouteWithChildren
  '/procurement': typeof AppProcurementRoute
  '/provisioning': typeof AppProvisioningRoute
  '/settings': typeof AppSettingsRoute
  '/small-boat-registration': typeof AppSmallBoatRegistrationRoute
  '/training': typeof AppTrainingRoute
  '/waypoint': typeof AppWaypointRoute
  '/yacht-it': typeof AppYachtItRoute
  '/crew-cab/drivers': typeof AppCrewCabDriversRoute
  '/crew-cab/locations': typeof AppCrewCabLocationsRoute
  '/crew-cab/trips': typeof AppCrewCabTripsRoute
  '/crew-cab/vehicles': typeof AppCrewCabVehiclesRoute
  '/crew-immigration/crew': typeof AppCrewImmigrationCrewRoute
  '/crew-immigration/documents': typeof AppCrewImmigrationDocumentsRoute
  '/crew-immigration/sign-on-off': typeof AppCrewImmigrationSignOnOffRoute
  '/crew-immigration/visas': typeof AppCrewImmigrationVisasRouteWithChildren
  '/orbit/$projectId': typeof AppOrbitProjectIdRoute
  '/packages/deliveries': typeof AppPackagesDeliveriesRoute
  '/packages/drivers': typeof AppPackagesDriversRoute
  '/permits/abu-dhabi': typeof AppPermitsAbuDhabiRoute
  '/permits/cruising-mothership': typeof AppPermitsCruisingMothershipRoute
  '/permits/cruising-tenders': typeof AppPermitsCruisingTendersRoute
  '/permits/dma': typeof AppPermitsDmaRoute
  '/permits/exit-entry': typeof AppPermitsExitEntryRoute
  '/permits/gate-pass': typeof AppPermitsGatePassRoute
  '/permits/navigation-license': typeof AppPermitsNavigationLicenseRoute
  '/permits/sanitation': typeof AppPermitsSanitationRoute
  '/permits/tdra': typeof AppPermitsTdraRoute
  '/yachts/$id': typeof AppYachtsIdRoute
  '/yachts/new': typeof AppYachtsNewRoute
  '/orbit/': typeof AppOrbitIndexRoute
  '/packages/': typeof AppPackagesIndexRoute
  '/yachts/': typeof AppYachtsIndexRoute
  '/crew-immigration/visas/new': typeof AppCrewImmigrationVisasNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-assistant': typeof AppAiAssistantRoute
  '/changelog': typeof AppChangelogRoute
  '/compass': typeof AppCompassRoute
  '/crew-cab': typeof AppCrewCabRouteWithChildren
  '/crew-immigration': typeof AppCrewImmigrationRouteWithChildren
  '/crew-placement': typeof AppCrewPlacementRoute
  '/director': typeof AppDirectorRoute
  '/finance': typeof AppFinanceRoute
  '/fleet-tracking': typeof AppFleetTrackingRoute
  '/procurement': typeof AppProcurementRoute
  '/provisioning': typeof AppProvisioningRoute
  '/settings': typeof AppSettingsRoute
  '/small-boat-registration': typeof AppSmallBoatRegistrationRoute
  '/training': typeof AppTrainingRoute
  '/waypoint': typeof AppWaypointRoute
  '/yacht-it': typeof AppYachtItRoute
  '/crew-cab/drivers': typeof AppCrewCabDriversRoute
  '/crew-cab/locations': typeof AppCrewCabLocationsRoute
  '/crew-cab/trips': typeof AppCrewCabTripsRoute
  '/crew-cab/vehicles': typeof AppCrewCabVehiclesRoute
  '/crew-immigration/crew': typeof AppCrewImmigrationCrewRoute
  '/crew-immigration/documents': typeof AppCrewImmigrationDocumentsRoute
  '/crew-immigration/sign-on-off': typeof AppCrewImmigrationSignOnOffRoute
  '/crew-immigration/visas': typeof AppCrewImmigrationVisasRouteWithChildren
  '/orbit/$projectId': typeof AppOrbitProjectIdRoute
  '/packages/deliveries': typeof AppPackagesDeliveriesRoute
  '/packages/drivers': typeof AppPackagesDriversRoute
  '/permits/abu-dhabi': typeof AppPermitsAbuDhabiRoute
  '/permits/cruising-mothership': typeof AppPermitsCruisingMothershipRoute
  '/permits/cruising-tenders': typeof AppPermitsCruisingTendersRoute
  '/permits/dma': typeof AppPermitsDmaRoute
  '/permits/exit-entry': typeof AppPermitsExitEntryRoute
  '/permits/gate-pass': typeof AppPermitsGatePassRoute
  '/permits/navigation-license': typeof AppPermitsNavigationLicenseRoute
  '/permits/sanitation': typeof AppPermitsSanitationRoute
  '/permits/tdra': typeof AppPermitsTdraRoute
  '/yachts/$id': typeof AppYachtsIdRoute
  '/yachts/new': typeof AppYachtsNewRoute
  '/orbit': typeof AppOrbitIndexRoute
  '/packages': typeof AppPackagesIndexRoute
  '/yachts': typeof AppYachtsIndexRoute
  '/crew-immigration/visas/new': typeof AppCrewImmigrationVisasNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/ai-assistant': typeof AppAiAssistantRoute
  '/_app/changelog': typeof AppChangelogRoute
  '/_app/compass': typeof AppCompassRoute
  '/_app/crew-cab': typeof AppCrewCabRouteWithChildren
  '/_app/crew-immigration': typeof AppCrewImmigrationRouteWithChildren
  '/_app/crew-placement': typeof AppCrewPlacementRoute
  '/_app/director': typeof AppDirectorRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/fleet-tracking': typeof AppFleetTrackingRoute
  '/_app/orbit': typeof AppOrbitRouteWithChildren
  '/_app/packages': typeof AppPackagesRouteWithChildren
  '/_app/procurement': typeof AppProcurementRoute
  '/_app/provisioning': typeof AppProvisioningRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/small-boat-registration': typeof AppSmallBoatRegistrationRoute
  '/_app/training': typeof AppTrainingRoute
  '/_app/waypoint': typeof AppWaypointRoute
  '/_app/yacht-it': typeof AppYachtItRoute
  '/_app/crew-cab/drivers': typeof AppCrewCabDriversRoute
  '/_app/crew-cab/locations': typeof AppCrewCabLocationsRoute
  '/_app/crew-cab/trips': typeof AppCrewCabTripsRoute
  '/_app/crew-cab/vehicles': typeof AppCrewCabVehiclesRoute
  '/_app/crew-immigration/crew': typeof AppCrewImmigrationCrewRoute
  '/_app/crew-immigration/documents': typeof AppCrewImmigrationDocumentsRoute
  '/_app/crew-immigration/sign-on-off': typeof AppCrewImmigrationSignOnOffRoute
  '/_app/crew-immigration/visas': typeof AppCrewImmigrationVisasRouteWithChildren
  '/_app/orbit/$projectId': typeof AppOrbitProjectIdRoute
  '/_app/packages/deliveries': typeof AppPackagesDeliveriesRoute
  '/_app/packages/drivers': typeof AppPackagesDriversRoute
  '/_app/permits/abu-dhabi': typeof AppPermitsAbuDhabiRoute
  '/_app/permits/cruising-mothership': typeof AppPermitsCruisingMothershipRoute
  '/_app/permits/cruising-tenders': typeof AppPermitsCruisingTendersRoute
  '/_app/permits/dma': typeof AppPermitsDmaRoute
  '/_app/permits/exit-entry': typeof AppPermitsExitEntryRoute
  '/_app/permits/gate-pass': typeof AppPermitsGatePassRoute
  '/_app/permits/navigation-license': typeof AppPermitsNavigationLicenseRoute
  '/_app/permits/sanitation': typeof AppPermitsSanitationRoute
  '/_app/permits/tdra': typeof AppPermitsTdraRoute
  '/_app/yachts/$id': typeof AppYachtsIdRoute
  '/_app/yachts/new': typeof AppYachtsNewRoute
  '/_app/orbit/': typeof AppOrbitIndexRoute
  '/_app/packages/': typeof AppPackagesIndexRoute
  '/_app/yachts/': typeof AppYachtsIndexRoute
  '/_app/crew-immigration/visas/new': typeof AppCrewImmigrationVisasNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai-assistant'
    | '/changelog'
    | '/compass'
    | '/crew-cab'
    | '/crew-immigration'
    | '/crew-placement'
    | '/director'
    | '/finance'
    | '/fleet-tracking'
    | '/orbit'
    | '/packages'
    | '/procurement'
    | '/provisioning'
    | '/settings'
    | '/small-boat-registration'
    | '/training'
    | '/waypoint'
    | '/yacht-it'
    | '/crew-cab/drivers'
    | '/crew-cab/locations'
    | '/crew-cab/trips'
    | '/crew-cab/vehicles'
    | '/crew-immigration/crew'
    | '/crew-immigration/documents'
    | '/crew-immigration/sign-on-off'
    | '/crew-immigration/visas'
    | '/orbit/$projectId'
    | '/packages/deliveries'
    | '/packages/drivers'
    | '/permits/abu-dhabi'
    | '/permits/cruising-mothership'
    | '/permits/cruising-tenders'
    | '/permits/dma'
    | '/permits/exit-entry'
    | '/permits/gate-pass'
    | '/permits/navigation-license'
    | '/permits/sanitation'
    | '/permits/tdra'
    | '/yachts/$id'
    | '/yachts/new'
    | '/orbit/'
    | '/packages/'
    | '/yachts/'
    | '/crew-immigration/visas/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ai-assistant'
    | '/changelog'
    | '/compass'
    | '/crew-cab'
    | '/crew-immigration'
    | '/crew-placement'
    | '/director'
    | '/finance'
    | '/fleet-tracking'
    | '/procurement'
    | '/provisioning'
    | '/settings'
    | '/small-boat-registration'
    | '/training'
    | '/waypoint'
    | '/yacht-it'
    | '/crew-cab/drivers'
    | '/crew-cab/locations'
    | '/crew-cab/trips'
    | '/crew-cab/vehicles'
    | '/crew-immigration/crew'
    | '/crew-immigration/documents'
    | '/crew-immigration/sign-on-off'
    | '/crew-immigration/visas'
    | '/orbit/$projectId'
    | '/packages/deliveries'
    | '/packages/drivers'
    | '/permits/abu-dhabi'
    | '/permits/cruising-mothership'
    | '/permits/cruising-tenders'
    | '/permits/dma'
    | '/permits/exit-entry'
    | '/permits/gate-pass'
    | '/permits/navigation-license'
    | '/permits/sanitation'
    | '/permits/tdra'
    | '/yachts/$id'
    | '/yachts/new'
    | '/orbit'
    | '/packages'
    | '/yachts'
    | '/crew-immigration/visas/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/ai-assistant'
    | '/_app/changelog'
    | '/_app/compass'
    | '/_app/crew-cab'
    | '/_app/crew-immigration'
    | '/_app/crew-placement'
    | '/_app/director'
    | '/_app/finance'
    | '/_app/fleet-tracking'
    | '/_app/orbit'
    | '/_app/packages'
    | '/_app/procurement'
    | '/_app/provisioning'
    | '/_app/settings'
    | '/_app/small-boat-registration'
    | '/_app/training'
    | '/_app/waypoint'
    | '/_app/yacht-it'
    | '/_app/crew-cab/drivers'
    | '/_app/crew-cab/locations'
    | '/_app/crew-cab/trips'
    | '/_app/crew-cab/vehicles'
    | '/_app/crew-immigration/crew'
    | '/_app/crew-immigration/documents'
    | '/_app/crew-immigration/sign-on-off'
    | '/_app/crew-immigration/visas'
    | '/_app/orbit/$projectId'
    | '/_app/packages/deliveries'
    | '/_app/packages/drivers'
    | '/_app/permits/abu-dhabi'
    | '/_app/permits/cruising-mothership'
    | '/_app/permits/cruising-tenders'
    | '/_app/permits/dma'
    | '/_app/permits/exit-entry'
    | '/_app/permits/gate-pass'
    | '/_app/permits/navigation-license'
    | '/_app/permits/sanitation'
    | '/_app/permits/tdra'
    | '/_app/yachts/$id'
    | '/_app/yachts/new'
    | '/_app/orbit/'
    | '/_app/packages/'
    | '/_app/yachts/'
    | '/_app/crew-immigration/visas/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/yacht-it': {
      id: '/_app/yacht-it'
      path: '/yacht-it'
      fullPath: '/yacht-it'
      preLoaderRoute: typeof AppYachtItRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/waypoint': {
      id: '/_app/waypoint'
      path: '/waypoint'
      fullPath: '/waypoint'
      preLoaderRoute: typeof AppWaypointRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/training': {
      id: '/_app/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AppTrainingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/small-boat-registration': {
      id: '/_app/small-boat-registration'
      path: '/small-boat-registration'
      fullPath: '/small-boat-registration'
      preLoaderRoute: typeof AppSmallBoatRegistrationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/provisioning': {
      id: '/_app/provisioning'
      path: '/provisioning'
      fullPath: '/provisioning'
      preLoaderRoute: typeof AppProvisioningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/procurement': {
      id: '/_app/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof AppProcurementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/packages': {
      id: '/_app/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AppPackagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orbit': {
      id: '/_app/orbit'
      path: '/orbit'
      fullPath: '/orbit'
      preLoaderRoute: typeof AppOrbitRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fleet-tracking': {
      id: '/_app/fleet-tracking'
      path: '/fleet-tracking'
      fullPath: '/fleet-tracking'
      preLoaderRoute: typeof AppFleetTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/director': {
      id: '/_app/director'
      path: '/director'
      fullPath: '/director'
      preLoaderRoute: typeof AppDirectorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crew-placement': {
      id: '/_app/crew-placement'
      path: '/crew-placement'
      fullPath: '/crew-placement'
      preLoaderRoute: typeof AppCrewPlacementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crew-immigration': {
      id: '/_app/crew-immigration'
      path: '/crew-immigration'
      fullPath: '/crew-immigration'
      preLoaderRoute: typeof AppCrewImmigrationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crew-cab': {
      id: '/_app/crew-cab'
      path: '/crew-cab'
      fullPath: '/crew-cab'
      preLoaderRoute: typeof AppCrewCabRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compass': {
      id: '/_app/compass'
      path: '/compass'
      fullPath: '/compass'
      preLoaderRoute: typeof AppCompassRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/changelog': {
      id: '/_app/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof AppChangelogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-assistant': {
      id: '/_app/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AppAiAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/yachts/': {
      id: '/_app/yachts/'
      path: '/yachts'
      fullPath: '/yachts/'
      preLoaderRoute: typeof AppYachtsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/packages/': {
      id: '/_app/packages/'
      path: '/'
      fullPath: '/packages/'
      preLoaderRoute: typeof AppPackagesIndexRouteImport
      parentRoute: typeof AppPackagesRoute
    }
    '/_app/orbit/': {
      id: '/_app/orbit/'
      path: '/'
      fullPath: '/orbit/'
      preLoaderRoute: typeof AppOrbitIndexRouteImport
      parentRoute: typeof AppOrbitRoute
    }
    '/_app/yachts/new': {
      id: '/_app/yachts/new'
      path: '/yachts/new'
      fullPath: '/yachts/new'
      preLoaderRoute: typeof AppYachtsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/yachts/$id': {
      id: '/_app/yachts/$id'
      path: '/yachts/$id'
      fullPath: '/yachts/$id'
      preLoaderRoute: typeof AppYachtsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits/tdra': {
      id: '/_app/permits/tdra'
      path: '/permits/tdra'
      fullPath: '/permits/tdra'
      preLoaderRoute: typeof AppPermitsTdraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits/sanitation': {
      id: '/_app/permits/sanitation'
      path: '/permits/sanitation'
      fullPath: '/permits/sanitation'
      preLoaderRoute: typeof AppPermitsSanitationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits/navigation-license': {
      id: '/_app/permits/navigation-license'
      path: '/permits/navigation-license'
      fullPath: '/permits/navigation-license'
      preLoaderRoute: typeof AppPermitsNavigationLicenseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits/gate-pass': {
      id: '/_app/permits/gate-pass'
      path: '/permits/gate-pass'
      fullPath: '/permits/gate-pass'
      preLoaderRoute: typeof AppPermitsGatePassRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits/exit-entry': {
      id: '/_app/permits/exit-entry'
      path: '/permits/exit-entry'
      fullPath: '/permits/exit-entry'
      preLoaderRoute: typeof AppPermitsExitEntryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits/dma': {
      id: '/_app/permits/dma'
      path: '/permits/dma'
      fullPath: '/permits/dma'
      preLoaderRoute: typeof AppPermitsDmaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits/cruising-tenders': {
      id: '/_app/permits/cruising-tenders'
      path: '/permits/cruising-tenders'
      fullPath: '/permits/cruising-tenders'
      preLoaderRoute: typeof AppPermitsCruisingTendersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits/cruising-mothership': {
      id: '/_app/permits/cruising-mothership'
      path: '/permits/cruising-mothership'
      fullPath: '/permits/cruising-mothership'
      preLoaderRoute: typeof AppPermitsCruisingMothershipRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits/abu-dhabi': {
      id: '/_app/permits/abu-dhabi'
      path: '/permits/abu-dhabi'
      fullPath: '/permits/abu-dhabi'
      preLoaderRoute: typeof AppPermitsAbuDhabiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/packages/drivers': {
      id: '/_app/packages/drivers'
      path: '/drivers'
      fullPath: '/packages/drivers'
      preLoaderRoute: typeof AppPackagesDriversRouteImport
      parentRoute: typeof AppPackagesRoute
    }
    '/_app/packages/deliveries': {
      id: '/_app/packages/deliveries'
      path: '/deliveries'
      fullPath: '/packages/deliveries'
      preLoaderRoute: typeof AppPackagesDeliveriesRouteImport
      parentRoute: typeof AppPackagesRoute
    }
    '/_app/orbit/$projectId': {
      id: '/_app/orbit/$projectId'
      path: '/$projectId'
      fullPath: '/orbit/$projectId'
      preLoaderRoute: typeof AppOrbitProjectIdRouteImport
      parentRoute: typeof AppOrbitRoute
    }
    '/_app/crew-immigration/visas': {
      id: '/_app/crew-immigration/visas'
      path: '/visas'
      fullPath: '/crew-immigration/visas'
      preLoaderRoute: typeof AppCrewImmigrationVisasRouteImport
      parentRoute: typeof AppCrewImmigrationRoute
    }
    '/_app/crew-immigration/sign-on-off': {
      id: '/_app/crew-immigration/sign-on-off'
      path: '/sign-on-off'
      fullPath: '/crew-immigration/sign-on-off'
      preLoaderRoute: typeof AppCrewImmigrationSignOnOffRouteImport
      parentRoute: typeof AppCrewImmigrationRoute
    }
    '/_app/crew-immigration/documents': {
      id: '/_app/crew-immigration/documents'
      path: '/documents'
      fullPath: '/crew-immigration/documents'
      preLoaderRoute: typeof AppCrewImmigrationDocumentsRouteImport
      parentRoute: typeof AppCrewImmigrationRoute
    }
    '/_app/crew-immigration/crew': {
      id: '/_app/crew-immigration/crew'
      path: '/crew'
      fullPath: '/crew-immigration/crew'
      preLoaderRoute: typeof AppCrewImmigrationCrewRouteImport
      parentRoute: typeof AppCrewImmigrationRoute
    }
    '/_app/crew-cab/vehicles': {
      id: '/_app/crew-cab/vehicles'
      path: '/vehicles'
      fullPath: '/crew-cab/vehicles'
      preLoaderRoute: typeof AppCrewCabVehiclesRouteImport
      parentRoute: typeof AppCrewCabRoute
    }
    '/_app/crew-cab/trips': {
      id: '/_app/crew-cab/trips'
      path: '/trips'
      fullPath: '/crew-cab/trips'
      preLoaderRoute: typeof AppCrewCabTripsRouteImport
      parentRoute: typeof AppCrewCabRoute
    }
    '/_app/crew-cab/locations': {
      id: '/_app/crew-cab/locations'
      path: '/locations'
      fullPath: '/crew-cab/locations'
      preLoaderRoute: typeof AppCrewCabLocationsRouteImport
      parentRoute: typeof AppCrewCabRoute
    }
    '/_app/crew-cab/drivers': {
      id: '/_app/crew-cab/drivers'
      path: '/drivers'
      fullPath: '/crew-cab/drivers'
      preLoaderRoute: typeof AppCrewCabDriversRouteImport
      parentRoute: typeof AppCrewCabRoute
    }
    '/_app/crew-immigration/visas/new': {
      id: '/_app/crew-immigration/visas/new'
      path: '/new'
      fullPath: '/crew-immigration/visas/new'
      preLoaderRoute: typeof AppCrewImmigrationVisasNewRouteImport
      parentRoute: typeof AppCrewImmigrationVisasRoute
    }
  }
}

interface AppCrewCabRouteChildren {
  AppCrewCabDriversRoute: typeof AppCrewCabDriversRoute
  AppCrewCabLocationsRoute: typeof AppCrewCabLocationsRoute
  AppCrewCabTripsRoute: typeof AppCrewCabTripsRoute
  AppCrewCabVehiclesRoute: typeof AppCrewCabVehiclesRoute
}

const AppCrewCabRouteChildren: AppCrewCabRouteChildren = {
  AppCrewCabDriversRoute: AppCrewCabDriversRoute,
  AppCrewCabLocationsRoute: AppCrewCabLocationsRoute,
  AppCrewCabTripsRoute: AppCrewCabTripsRoute,
  AppCrewCabVehiclesRoute: AppCrewCabVehiclesRoute,
}

const AppCrewCabRouteWithChildren = AppCrewCabRoute._addFileChildren(
  AppCrewCabRouteChildren,
)

interface AppCrewImmigrationVisasRouteChildren {
  AppCrewImmigrationVisasNewRoute: typeof AppCrewImmigrationVisasNewRoute
}

const AppCrewImmigrationVisasRouteChildren: AppCrewImmigrationVisasRouteChildren =
  {
    AppCrewImmigrationVisasNewRoute: AppCrewImmigrationVisasNewRoute,
  }

const AppCrewImmigrationVisasRouteWithChildren =
  AppCrewImmigrationVisasRoute._addFileChildren(
    AppCrewImmigrationVisasRouteChildren,
  )

interface AppCrewImmigrationRouteChildren {
  AppCrewImmigrationCrewRoute: typeof AppCrewImmigrationCrewRoute
  AppCrewImmigrationDocumentsRoute: typeof AppCrewImmigrationDocumentsRoute
  AppCrewImmigrationSignOnOffRoute: typeof AppCrewImmigrationSignOnOffRoute
  AppCrewImmigrationVisasRoute: typeof AppCrewImmigrationVisasRouteWithChildren
}

const AppCrewImmigrationRouteChildren: AppCrewImmigrationRouteChildren = {
  AppCrewImmigrationCrewRoute: AppCrewImmigrationCrewRoute,
  AppCrewImmigrationDocumentsRoute: AppCrewImmigrationDocumentsRoute,
  AppCrewImmigrationSignOnOffRoute: AppCrewImmigrationSignOnOffRoute,
  AppCrewImmigrationVisasRoute: AppCrewImmigrationVisasRouteWithChildren,
}

const AppCrewImmigrationRouteWithChildren =
  AppCrewImmigrationRoute._addFileChildren(AppCrewImmigrationRouteChildren)

interface AppOrbitRouteChildren {
  AppOrbitProjectIdRoute: typeof AppOrbitProjectIdRoute
  AppOrbitIndexRoute: typeof AppOrbitIndexRoute
}

const AppOrbitRouteChildren: AppOrbitRouteChildren = {
  AppOrbitProjectIdRoute: AppOrbitProjectIdRoute,
  AppOrbitIndexRoute: AppOrbitIndexRoute,
}

const AppOrbitRouteWithChildren = AppOrbitRoute._addFileChildren(
  AppOrbitRouteChildren,
)

interface AppPackagesRouteChildren {
  AppPackagesDeliveriesRoute: typeof AppPackagesDeliveriesRoute
  AppPackagesDriversRoute: typeof AppPackagesDriversRoute
  AppPackagesIndexRoute: typeof AppPackagesIndexRoute
}

const AppPackagesRouteChildren: AppPackagesRouteChildren = {
  AppPackagesDeliveriesRoute: AppPackagesDeliveriesRoute,
  AppPackagesDriversRoute: AppPackagesDriversRoute,
  AppPackagesIndexRoute: AppPackagesIndexRoute,
}

const AppPackagesRouteWithChildren = AppPackagesRoute._addFileChildren(
  AppPackagesRouteChildren,
)

interface AppRouteChildren {
  AppAiAssistantRoute: typeof AppAiAssistantRoute
  AppChangelogRoute: typeof AppChangelogRoute
  AppCompassRoute: typeof AppCompassRoute
  AppCrewCabRoute: typeof AppCrewCabRouteWithChildren
  AppCrewImmigrationRoute: typeof AppCrewImmigrationRouteWithChildren
  AppCrewPlacementRoute: typeof AppCrewPlacementRoute
  AppDirectorRoute: typeof AppDirectorRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppFleetTrackingRoute: typeof AppFleetTrackingRoute
  AppOrbitRoute: typeof AppOrbitRouteWithChildren
  AppPackagesRoute: typeof AppPackagesRouteWithChildren
  AppProcurementRoute: typeof AppProcurementRoute
  AppProvisioningRoute: typeof AppProvisioningRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSmallBoatRegistrationRoute: typeof AppSmallBoatRegistrationRoute
  AppTrainingRoute: typeof AppTrainingRoute
  AppWaypointRoute: typeof AppWaypointRoute
  AppYachtItRoute: typeof AppYachtItRoute
  AppPermitsAbuDhabiRoute: typeof AppPermitsAbuDhabiRoute
  AppPermitsCruisingMothershipRoute: typeof AppPermitsCruisingMothershipRoute
  AppPermitsCruisingTendersRoute: typeof AppPermitsCruisingTendersRoute
  AppPermitsDmaRoute: typeof AppPermitsDmaRoute
  AppPermitsExitEntryRoute: typeof AppPermitsExitEntryRoute
  AppPermitsGatePassRoute: typeof AppPermitsGatePassRoute
  AppPermitsNavigationLicenseRoute: typeof AppPermitsNavigationLicenseRoute
  AppPermitsSanitationRoute: typeof AppPermitsSanitationRoute
  AppPermitsTdraRoute: typeof AppPermitsTdraRoute
  AppYachtsIdRoute: typeof AppYachtsIdRoute
  AppYachtsNewRoute: typeof AppYachtsNewRoute
  AppYachtsIndexRoute: typeof AppYachtsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiAssistantRoute: AppAiAssistantRoute,
  AppChangelogRoute: AppChangelogRoute,
  AppCompassRoute: AppCompassRoute,
  AppCrewCabRoute: AppCrewCabRouteWithChildren,
  AppCrewImmigrationRoute: AppCrewImmigrationRouteWithChildren,
  AppCrewPlacementRoute: AppCrewPlacementRoute,
  AppDirectorRoute: AppDirectorRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppFleetTrackingRoute: AppFleetTrackingRoute,
  AppOrbitRoute: AppOrbitRouteWithChildren,
  AppPackagesRoute: AppPackagesRouteWithChildren,
  AppProcurementRoute: AppProcurementRoute,
  AppProvisioningRoute: AppProvisioningRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSmallBoatRegistrationRoute: AppSmallBoatRegistrationRoute,
  AppTrainingRoute: AppTrainingRoute,
  AppWaypointRoute: AppWaypointRoute,
  AppYachtItRoute: AppYachtItRoute,
  AppPermitsAbuDhabiRoute: AppPermitsAbuDhabiRoute,
  AppPermitsCruisingMothershipRoute: AppPermitsCruisingMothershipRoute,
  AppPermitsCruisingTendersRoute: AppPermitsCruisingTendersRoute,
  AppPermitsDmaRoute: AppPermitsDmaRoute,
  AppPermitsExitEntryRoute: AppPermitsExitEntryRoute,
  AppPermitsGatePassRoute: AppPermitsGatePassRoute,
  AppPermitsNavigationLicenseRoute: AppPermitsNavigationLicenseRoute,
  AppPermitsSanitationRoute: AppPermitsSanitationRoute,
  AppPermitsTdraRoute: AppPermitsTdraRoute,
  AppYachtsIdRoute: AppYachtsIdRoute,
  AppYachtsNewRoute: AppYachtsNewRoute,
  AppYachtsIndexRoute: AppYachtsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
